// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.lpadd.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.lpadd.*
import java.io.File

public class LpaddCliCommand(
    private val useCase: ExecuteUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "lpadd") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ExecuteUseCase(repository), context)

    override fun help(context: Context): String = "Execute the tool with its options and positional operands"

    public val readonly: Boolean by option("--readonly", help = "The partition should be mapped read-only.").flag()
    public val replace: Boolean by option("--replace", help = "The partition contents should be replaced with").flag()
    public val positionalArgs: List<String> by argument(name = "positionalArgs", help = "Tool-specific positional operands").multiple()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                readonly = readonly,
                replace = replace,
                positionalArgs = positionalArgs
            )
        }
    }
}
