// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.apktool.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.apktool.*
import java.io.File

public class CfCliCommand(
    private val useCase: CfUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "cf") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(CfUseCase(repository), context)

    override fun help(context: Context): String = "Unrecognized option: -h"

    public val aapt: File? by option("--aapt", help = "Use aapt2 binary located in <file>.").convert { File(it) }
    public val all: Boolean by option("--all", help = "Include all framework files regardless of tag.").flag()
    public val allSrc: Boolean by option("--all-src", "-a", help = "Decode all sources in the apk (includes unknown dex files).").flag()
    public val copyOriginal: Boolean by option("--copy-original", help = "Copy original AndroidManifest.xml and META-INF. See project page for more info.").flag()
    public val debuggable: Boolean by option("--debuggable", help = "Set android:debuggable to \"true\" in AndroidManifest.xml for the built apk.").flag()
    public val force: Boolean by option("--force", "-f", help = "Force delete destination directory.").flag()
    public val framePath: File? by option("--frame-path", "-p", help = "Use framework files located in <dir>.").convert { File(it) }
    public val frameTag: String? by option("--frame-tag", "-t", help = "Use framework files tagged with <tag>.")
    public val ignoreRawValues: Boolean by option("--ignore-raw-values", help = "Ignore raw attribute values in XML resource files.").flag()
    public val jobs: Int? by option("--jobs", "-j", help = "Set the number of jobs to execute in parallel to <num>.").int()
    public val keepBrokenRes: Boolean by option("--keep-broken-res", help = "Use if there was an error and some resources were dropped, e.g. \"Invalid resource config detected. Dropping resources\", but you want to decode them anyway, even with errors. You will have to fix them manually before building.").flag()
    public val lib: List<String> by option("--lib", "-l", help = "Use shared library <package> located in <file>. Can be specified multiple times.").multiple()
    public val matchOriginal: Boolean by option("--match-original", help = "Keep files closest to original as possible (prevents rebuild).").flag()
    public val netSecConf: Boolean by option("--net-sec-conf", help = "Add a generic network security configuration file to the built apk.").flag()
    public val noApk: Boolean by option("--no-apk", help = "Disable repacking of the built files into a new apk.").flag()
    public val noAssets: Boolean by option("--no-assets", help = "Do not decode assets.").flag()
    public val noCrunch: Boolean by option("--no-crunch", help = "Disable crunching of resource files during the build step.").flag()
    public val noDebugInfo: Boolean by option("--no-debug-info", help = "Do not include debug info in sources (.local, .param, .line, etc.)").flag()
    public val noRes: Boolean by option("--no-res", "-r", help = "Do not decode resources.").flag()
    public val noSrc: Boolean by option("--no-src", "-s", help = "Do not decode sources.").flag()
    public val onlyManifest: Boolean by option("--only-manifest", help = "Only decode AndroidManifest.xml without resources.").flag()
    public val output: File? by option("--output", "-o", help = "Output decoded files to <dir>. (default: apk.out)").convert { File(it) }
    public val quiet: Boolean by option("--quiet", "-q", help = "Suppress normal output.").flag()
    public val resResolveMode: String? by option("--res-resolve-mode", help = "Set the resolve mode for resources to <mode>. Possible values: 'default', 'greedy' or 'lazy'.")
    public val verbose: Boolean by option("--verbose", "-v", help = "Increase output verbosity.").flag()
    public val brutAlllGmailCom: String by argument(name = "brutAlllGmailCom", help = "Positional brut.alll@gmail.com accepted by the tool")

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                aapt = aapt,
                all = all,
                allSrc = allSrc,
                copyOriginal = copyOriginal,
                debuggable = debuggable,
                force = force,
                framePath = framePath,
                frameTag = frameTag,
                ignoreRawValues = ignoreRawValues,
                jobs = jobs,
                keepBrokenRes = keepBrokenRes,
                lib = lib,
                matchOriginal = matchOriginal,
                netSecConf = netSecConf,
                noApk = noApk,
                noAssets = noAssets,
                noCrunch = noCrunch,
                noDebugInfo = noDebugInfo,
                noRes = noRes,
                noSrc = noSrc,
                onlyManifest = onlyManifest,
                output = output,
                quiet = quiet,
                resResolveMode = resResolveMode,
                verbose = verbose,
                brutAlllGmailCom = brutAlllGmailCom
            )
        }
    }
}
