// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.erofsfuse

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class ExecuteCommand(
    public val D: Boolean = false,
    public val F: Boolean = false,
    public val O: List<String> = emptyList(),
    public val S: Boolean = false,
    public val dbglevel: String? = null,
    public val device: String? = null,
    public val help: Boolean = false,
    public val offset: String? = null,
    public val version: Boolean = false,
    public val positionalArgs: List<String> = emptyList()
) : ToolCommand<String> {

    override val toolId: ToolId get() = ToolId.EROFSFUSE
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<String> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("identity") as io.ltirom.tooling.core.ToolOutputParser<String>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): String {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        if (D) args.add("-d")
        if (F) args.add("-f")
        for (item in O) {
            args.add("-o")
            args.add(item.toString())
        }
        if (S) args.add("-s")
        dbglevel?.let { val value = it
            args.add("--dbglevel")
            args.add(value.toString())
        }
        device?.let { val value = it
            args.add("--device")
            args.add(value.toString())
        }
        if (help) args.add("--help")
        offset?.let { val value = it
            args.add("--offset")
            args.add(value.toString())
        }
        if (version) args.add("--version")
        for (item in positionalArgs) {
            args.add(item.toString())
        }
        return args
    }
}
