// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.ext2simg.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.ext2simg.*
import java.io.File

public class Ext2simgCliCommand(
    private val useCase: ExecuteUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "ext2simg") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ExecuteUseCase(repository), context)

    override fun help(context: Context): String = "Execute the tool with its options and positional operands"

    public val C: Boolean by option("--c", "-c", help = "include CRC block").flag()
    public val S: Boolean by option("--s", "-S", help = "don't use sparse output format").flag()
    public val Z: Boolean by option("--z", "-z", help = "gzip output").flag()
    public val positionalArgs: List<String> by argument(name = "positionalArgs", help = "Tool-specific positional operands").multiple()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                C = C,
                S = S,
                Z = Z,
                positionalArgs = positionalArgs
            )
        }
    }
}
