// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.mkbootfs

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class ExecuteCommand(
    public val dirname: File? = null,
    public val file: File? = null,
    public val help: Boolean = false,
    public val nodes: File? = null,
    public val positionalArgs: List<String> = emptyList()
) : ToolCommand<String> {

    override val toolId: ToolId get() = ToolId.MKBOOTFS
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<String> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("identity") as io.ltirom.tooling.core.ToolOutputParser<String>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): String {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        dirname?.let { val value = it
            args.add("--dirname")
            args.add(value.toString())
        }
        file?.let { val value = it
            args.add("--file")
            args.add(value.toString())
        }
        if (help) args.add("--help")
        nodes?.let { val value = it
            args.add("--nodes")
            args.add(value.toString())
        }
        for (item in positionalArgs) {
            args.add(item.toString())
        }
        return args
    }
}
