// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.sload_f2fs.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.sload_f2fs.*
import java.io.File

public class Sload_f2fsCliCommand(
    private val useCase: ExecuteUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "sload_f2fs") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ExecuteUseCase(repository), context)

    override fun help(context: Context): String = "Execute the tool with its options and positional operands"

    public val A: String? by option("--a", "-a", help = "<algorithm> compression algorithm, default LZ4")
    public val C: String? by option("--c", "-C", help = "fs_config")
    public val F: String? by option("--f", "-f", help = "source directory [path of the source directory]")
    public val I: String? by option("--i", "-i", help = "<ext> compress files with these extensions only.")
    public val L: String? by option("--l", "-L", help = "<log-of-blocks-per-cluster>, default 2")
    public val M: String? by option("--m", "-m", help = "<num> min compressed blocks per cluster")
    public val P: String? by option("--p", "-p", help = "product out directory")
    public val R: Boolean by option("--r", "-r", help = "read only (to release unused blocks) for compressed files").flag()
    public val S: String? by option("--s", "-s", help = "file_contexts")
    public val T: String? by option("--t", "-t", help = "mount point [prefix of target fs path, default:/]")
    public val X: String? by option("--x", "-x", help = "<ext> compress files except for these extensions.")
    public val positionalArgs: List<String> by argument(name = "positionalArgs", help = "Tool-specific positional operands").multiple()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                A = A,
                C = C,
                F = F,
                I = I,
                L = L,
                M = M,
                P = P,
                R = R,
                S = S,
                T = T,
                X = X,
                positionalArgs = positionalArgs
            )
        }
    }
}
