// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.make_f2fs.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.make_f2fs.*
import java.io.File

public class Make_f2fsCliCommand(
    private val useCase: ExecuteUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "make_f2fs") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ExecuteUseCase(repository), context)

    override fun help(context: Context): String = "Execute the tool with its options and positional operands"

    public val B: String? by option("--b", "-b", help = "filesystem block size [default:4096]")
    public val C: List<String> by option("--c", "-c", help = "[device_name[@alias_filename]] up to 7 additional devices, except meta device").multiple()
    public val D: String? by option("--d", "-d", help = "debug level [default:0]")
    public val E: String? by option("--e", "-e", help = "[cold file ext list] e.g. \"mp3,gif,mov\"")
    public val F: Boolean by option("--f", "-f", help = "force overwrite of the existing filesystem").flag()
    public val G: String? by option("--g", "-g", help = "add default options")
    public val H: Boolean by option("--h", "-H", help = "support write hint").flag()
    public val I: Boolean by option("--i", "-i", help = "extended node bitmap, node ratio is 20% by default").flag()
    public val L: String? by option("--l", "-l", help = "label")
    public val M: Boolean by option("--m", "-m", help = "support zoned block device [default:0]").flag()
    public val O: String? by option("--o", "-o", help = "overprovision percentage [default:auto]")
    public val Q: Boolean by option("--q", "-q", help = "quiet mode").flag()
    public val R: Boolean by option("--r", "-r", help = "set checkpointing seed (srand()) to 0").flag()
    public val S: String? by option("--s", "-s", help = "# of segments per section [default:1]")
    public val T: String? by option("--t", "-t", help = "0: nodiscard, 1: discard [default:1]")
    public val U: String? by option("--u", "-U", help = "uuid")
    public val V: Boolean by option("--v", "-V", help = "print the version number and exit").flag()
    public val W: String? by option("--w", "-w", help = "wanted sector size")
    public val Z: String? by option("--z", "-z", help = "# of sections per zone [default:1]")
    public val positionalArgs: List<String> by argument(name = "positionalArgs", help = "Tool-specific positional operands").multiple()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                B = B,
                C = C,
                D = D,
                E = E,
                F = F,
                G = G,
                H = H,
                I = I,
                L = L,
                M = M,
                O = O,
                Q = Q,
                R = R,
                S = S,
                T = T,
                U = U,
                V = V,
                W = W,
                Z = Z,
                positionalArgs = positionalArgs
            )
        }
    }
}
