// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class AliasSetCliCommand(
    private val useCase: AliasSetUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "set") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(AliasSetUseCase(repository), context)

    override fun help(context: Context): String = "Define a word that will expand to a full gh command when invoked."

    public val clobber: Boolean by option("--clobber", help = "Overwrite existing aliases of the same name").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val shell: Boolean by option("--shell", "-s", help = "Declare an alias to be passed through a shell interpreter").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                clobber = clobber,
                help = help,
                shell = shell,
                version = version
            )
        }
    }
}
