// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class AttestationTrustedRootCliCommand(
    private val useCase: AttestationTrustedRootUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "trusted-root") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(AttestationTrustedRootUseCase(repository), context)

    override fun help(context: Context): String = "Output contents for a trusted_root.jsonl file, likely for offline verification."

    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val hostname: Boolean by option("--hostname", help = "string   Configure host to use").flag()
    public val tufRoot: Boolean by option("--tuf-root", help = "string   Path to the TUF root.json file on disk").flag()
    public val tufUrl: Boolean by option("--tuf-url", help = "string    URL to the TUF repository mirror").flag()
    public val verifyOnly: Boolean by option("--verify-only", help = "Don't output trusted_root.jsonl contents").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                hostname = hostname,
                tufRoot = tufRoot,
                tufUrl = tufUrl,
                verifyOnly = verifyOnly,
                version = version
            )
        }
    }
}
