// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class AttestationVerifyCliCommand(
    private val useCase: AttestationVerifyUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "verify") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(AttestationVerifyUseCase(repository), context)

    override fun help(context: Context): String = "Verify the integrity and provenance of an artifact using its associated"

    public val bundle: Boolean by option("--bundle", "-b", help = "string                Path to bundle on disk, either a single bundle in a JSON file or a JSON lines file with multiple bundles").flag()
    public val bundleFromOci: Boolean by option("--bundle-from-oci", help = "When verifying an OCI image, fetch the attestation bundle from the OCI registry instead of from GitHub").flag()
    public val certIdentity: Boolean by option("--cert-identity", help = "string         Enforce that the certificate's SubjectAlternativeName matches the provided value exactly").flag()
    public val certIdentityRegex: Boolean by option("--cert-identity-regex", "-i", help = "string   Enforce that the certificate's SubjectAlternativeName matches the provided regex").flag()
    public val certOidcIssuer: Boolean by option("--cert-oidc-issuer", help = "string      Enforce that the issuer of the OIDC token matches the provided value (default \"https://token.actions.githubusercontent.com\")").flag()
    public val customTrustedRoot: Boolean by option("--custom-trusted-root", help = "string   Path to a trusted_root.jsonl file; likely for offline verification").flag()
    public val denySelfHostedRunners: Boolean by option("--deny-self-hosted-runners", help = "Fail verification for attestations generated on self-hosted runners").flag()
    public val digestAlg: Boolean by option("--digest-alg", "-d", help = "string            The algorithm used to compute a digest of the artifact: {sha256|sha512} (default \"sha256\")").flag()
    public val format: Boolean by option("--format", help = "string                Output format: {json}").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val hostname: Boolean by option("--hostname", help = "string              Configure host to use").flag()
    public val jq: Boolean by option("--jq", "-q", help = "expression                Filter JSON output using a jq expression").flag()
    public val limit: Boolean by option("--limit", "-L", help = "int                    Maximum number of attestations to fetch (default 30)").flag()
    public val noPublicGood: Boolean by option("--no-public-good", help = "Do not verify attestations signed with Sigstore public good instance").flag()
    public val owner: Boolean by option("--owner", "-o", help = "string                 GitHub organization to scope attestation lookup by").flag()
    public val predicateType: Boolean by option("--predicate-type", help = "string        Enforce that verified attestations' predicate type matches the provided value (default \"https://slsa.dev/provenance/v1\")").flag()
    public val repo: Boolean by option("--repo", "-R", help = "string                  Repository name in the format <owner>/<repo>").flag()
    public val signerDigest: Boolean by option("--signer-digest", help = "string         Enforce that the digest associated with the signer workflow matches the provided value").flag()
    public val signerRepo: Boolean by option("--signer-repo", help = "string           Enforce that the workflow that signed the attestation's repository matches the provided value (<owner>/<repo>)").flag()
    public val signerWorkflow: Boolean by option("--signer-workflow", help = "string       Enforce that the workflow that signed the attestation matches the provided value ([host/]<owner>/<repo>/<path>/<to>/<workflow>)").flag()
    public val sourceDigest: Boolean by option("--source-digest", help = "string         Enforce that the digest associated with the source repository matches the provided value").flag()
    public val sourceRef: Boolean by option("--source-ref", help = "string            Enforce that the git ref associated with the source repository matches the provided value").flag()
    public val template: Boolean by option("--template", "-t", help = "string              Format JSON output using a Go template; see \"gh help formatting\"").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                bundle = bundle,
                bundleFromOci = bundleFromOci,
                certIdentity = certIdentity,
                certIdentityRegex = certIdentityRegex,
                certOidcIssuer = certOidcIssuer,
                customTrustedRoot = customTrustedRoot,
                denySelfHostedRunners = denySelfHostedRunners,
                digestAlg = digestAlg,
                format = format,
                help = help,
                hostname = hostname,
                jq = jq,
                limit = limit,
                noPublicGood = noPublicGood,
                owner = owner,
                predicateType = predicateType,
                repo = repo,
                signerDigest = signerDigest,
                signerRepo = signerRepo,
                signerWorkflow = signerWorkflow,
                sourceDigest = sourceDigest,
                sourceRef = sourceRef,
                template = template,
                version = version
            )
        }
    }
}
