// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class AuthLogoutCliCommand(
    private val useCase: AuthLogoutUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "logout") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(AuthLogoutUseCase(repository), context)

    override fun help(context: Context): String = "Remove authentication for a GitHub account."

    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val hostname: Boolean by option("--hostname", "-h", help = "string   The hostname of the GitHub instance to log out of").flag()
    public val user: Boolean by option("--user", "-u", help = "string       The account to log out of").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                hostname = hostname,
                user = user,
                version = version
            )
        }
    }
}
