// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class CodespacePortsCliCommand(
    private val useCase: CodespacePortsUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "ports") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(CodespacePortsUseCase(repository), context)

    override fun help(context: Context): String = "List ports in a codespace"

    public val codespace: Boolean by option("--codespace", "-c", help = "string    Name of the codespace").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val jq: Boolean by option("--jq", "-q", help = "expression       Filter JSON output using a jq expression").flag()
    public val json: Boolean by option("--json", help = "fields         Output JSON with the specified fields").flag()
    public val repo: Boolean by option("--repo", "-R", help = "string         Filter codespace selection by repository name (user/repo)").flag()
    public val repoOwner: Boolean by option("--repo-owner", help = "string   Filter codespace selection by repository owner (username or org)").flag()
    public val template: Boolean by option("--template", "-t", help = "string     Format JSON output using a Go template; see \"gh help formatting\"").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                codespace = codespace,
                help = help,
                jq = jq,
                json = json,
                repo = repo,
                repoOwner = repoOwner,
                template = template,
                version = version
            )
        }
    }
}
