// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class CodespaceCreateCliCommand(
    private val useCase: CodespaceCreateUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "create") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(CodespaceCreateUseCase(repository), context)

    override fun help(context: Context): String = "Create a codespace"

    public val branch: Boolean by option("--branch", "-b", help = "string               Repository branch").flag()
    public val defaultPermissions: Boolean by option("--default-permissions", help = "Do not prompt to accept additional permissions requested by the codespace").flag()
    public val devcontainerPath: Boolean by option("--devcontainer-path", help = "string    Path to the devcontainer.json file to use when creating codespace").flag()
    public val displayName: Boolean by option("--display-name", "-d", help = "string         Display name for the codespace (48 characters or less)").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val idleTimeout: Boolean by option("--idle-timeout", help = "duration       Allowed inactivity before codespace is stopped, e.g. \"10m\", \"1h\"").flag()
    public val location: Boolean by option("--location", "-l", help = "string             Location: {EastUs|SouthEastAsia|WestEurope|WestUs2} (determined automatically if not provided)").flag()
    public val machine: Boolean by option("--machine", "-m", help = "string              Hardware specifications for the VM").flag()
    public val repo: Boolean by option("--repo", "-R", help = "string                 Repository name with owner: user/repo").flag()
    public val retentionPeriod: Boolean by option("--retention-period", help = "duration   Allowed time after shutting down before the codespace is automatically deleted (maximum 30 days), e.g. \"1h\", \"72h\"").flag()
    public val status: Boolean by option("--status", "-s", help = "Show status of post-create command and dotfiles").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()
    public val web: Boolean by option("--web", "-w", help = "Create codespace from browser, cannot be used with --display-name, --idle-timeout, or --retention-period").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                branch = branch,
                defaultPermissions = defaultPermissions,
                devcontainerPath = devcontainerPath,
                displayName = displayName,
                help = help,
                idleTimeout = idleTimeout,
                location = location,
                machine = machine,
                repo = repo,
                retentionPeriod = retentionPeriod,
                status = status,
                version = version,
                web = web
            )
        }
    }
}
