// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class CompletionCliCommand(
    private val useCase: CompletionUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "completion") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(CompletionUseCase(repository), context)

    override fun help(context: Context): String = "Generate shell completion scripts for GitHub CLI commands."

    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val shell: Boolean by option("--shell", "-s", help = "string   Shell type: {bash|zsh|fish|powershell}").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                shell = shell,
                version = version
            )
        }
    }
}
