// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class ExtensionSearchCliCommand(
    private val useCase: ExtensionSearchUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "search") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ExtensionSearchUseCase(repository), context)

    override fun help(context: Context): String = "Search for gh extensions."

    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val jq: Boolean by option("--jq", "-q", help = "expression     Filter JSON output using a jq expression").flag()
    public val json: Boolean by option("--json", help = "fields       Output JSON with the specified fields").flag()
    public val license: Boolean by option("--license", help = "strings   Filter based on license type").flag()
    public val limit: Boolean by option("--limit", "-L", help = "int         Maximum number of extensions to fetch (default 30)").flag()
    public val order: Boolean by option("--order", help = "string      Order of repositories returned, ignored unless '--sort' flag is specified: {asc|desc} (default \"desc\")").flag()
    public val owner: Boolean by option("--owner", help = "strings     Filter on owner").flag()
    public val sort: Boolean by option("--sort", help = "string       Sort fetched repositories: {forks|help-wanted-issues|stars|updated} (default \"best-match\")").flag()
    public val template: Boolean by option("--template", "-t", help = "string   Format JSON output using a Go template; see \"gh help formatting\"").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()
    public val web: Boolean by option("--web", "-w", help = "Open the search query in the web browser").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                jq = jq,
                json = json,
                license = license,
                limit = limit,
                order = order,
                owner = owner,
                sort = sort,
                template = template,
                version = version,
                web = web
            )
        }
    }
}
