// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class ExtensionExecCliCommand(
    private val useCase: ExtensionExecUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "exec") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ExtensionExecUseCase(repository), context)

    override fun help(context: Context): String = "extension \"--help\" not found"

    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                version = version
            )
        }
    }
}
