// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class LabelCloneCliCommand(
    private val useCase: LabelCloneUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "clone") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(LabelCloneUseCase(repository), context)

    override fun help(context: Context): String = "Clones labels from a source repository to a destination repository on GitHub."

    public val force: Boolean by option("--force", "-f", help = "Overwrite labels in the destination repository").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val repo: Boolean by option("--repo", "-R", help = "[HOST/]OWNER/REPO   Select another repository using the [HOST/]OWNER/REPO format").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                force = force,
                help = help,
                repo = repo,
                version = version
            )
        }
    }
}
