// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class LabelListCliCommand(
    private val useCase: LabelListUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "list") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(LabelListUseCase(repository), context)

    override fun help(context: Context): String = "Display labels in a GitHub repository."

    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val jq: Boolean by option("--jq", "-q", help = "expression     Filter JSON output using a jq expression").flag()
    public val json: Boolean by option("--json", help = "fields       Output JSON with the specified fields").flag()
    public val limit: Boolean by option("--limit", "-L", help = "int         Maximum number of labels to fetch (default 30)").flag()
    public val order: Boolean by option("--order", help = "string      Order of labels returned: {asc|desc} (default \"asc\")").flag()
    public val repo: Boolean by option("--repo", "-R", help = "[HOST/]OWNER/REPO   Select another repository using the [HOST/]OWNER/REPO format").flag()
    public val search: Boolean by option("--search", "-S", help = "string     Search label names and descriptions").flag()
    public val sort: Boolean by option("--sort", help = "string       Sort fetched labels: {created|name} (default \"created\")").flag()
    public val template: Boolean by option("--template", "-t", help = "string   Format JSON output using a Go template; see \"gh help formatting\"").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()
    public val web: Boolean by option("--web", "-w", help = "List labels in the web browser").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                jq = jq,
                json = json,
                limit = limit,
                order = order,
                repo = repo,
                search = search,
                sort = sort,
                template = template,
                version = version,
                web = web
            )
        }
    }
}
