// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class ProjectEditCliCommand(
    private val useCase: ProjectEditUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "edit") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ProjectEditUseCase(repository), context)

    override fun help(context: Context): String = "Edit a project"

    public val description: Boolean by option("--description", "-d", help = "string   New description of the project").flag()
    public val format: Boolean by option("--format", help = "string        Output format: {json}").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val jq: Boolean by option("--jq", "-q", help = "expression        Filter JSON output using a jq expression").flag()
    public val owner: Boolean by option("--owner", help = "string         Login of the owner. Use \"@me\" for the current user.").flag()
    public val readme: Boolean by option("--readme", help = "string        New readme for the project").flag()
    public val template: Boolean by option("--template", "-t", help = "string      Format JSON output using a Go template; see \"gh help formatting\"").flag()
    public val title: Boolean by option("--title", help = "string         New title for the project").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()
    public val visibility: Boolean by option("--visibility", help = "string    Change project visibility: {PUBLIC|PRIVATE}").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                description = description,
                format = format,
                help = help,
                jq = jq,
                owner = owner,
                readme = readme,
                template = template,
                title = title,
                version = version,
                visibility = visibility
            )
        }
    }
}
