// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class ProjectCopyCliCommand(
    private val useCase: ProjectCopyUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "copy") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ProjectCopyUseCase(repository), context)

    override fun help(context: Context): String = "Copy a project"

    public val drafts: Boolean by option("--drafts", help = "Include draft issues when copying").flag()
    public val format: Boolean by option("--format", help = "string         Output format: {json}").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val jq: Boolean by option("--jq", "-q", help = "expression         Filter JSON output using a jq expression").flag()
    public val sourceOwner: Boolean by option("--source-owner", help = "string   Login of the source owner. Use \"@me\" for the current user.").flag()
    public val targetOwner: Boolean by option("--target-owner", help = "string   Login of the target owner. Use \"@me\" for the current user.").flag()
    public val template: Boolean by option("--template", "-t", help = "string       Format JSON output using a Go template; see \"gh help formatting\"").flag()
    public val title: Boolean by option("--title", help = "string          Title for the new project").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                drafts = drafts,
                format = format,
                help = help,
                jq = jq,
                sourceOwner = sourceOwner,
                targetOwner = targetOwner,
                template = template,
                title = title,
                version = version
            )
        }
    }
}
