// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class ProjectItemEditCliCommand(
    private val useCase: ProjectItemEditUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "item-edit") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ProjectItemEditUseCase(repository), context)

    override fun help(context: Context): String = "Edit a draft issue or a project item."

    public val body: Boolean by option("--body", help = "string                      Body of the draft issue item").flag()
    public val clear: Boolean by option("--clear", help = "Remove field value").flag()
    public val date: Boolean by option("--date", help = "string                      Date value for the field (YYYY-MM-DD)").flag()
    public val field: Boolean by option("--field", help = "string                     Name of the field to update").flag()
    public val fieldId: Boolean by option("--field-id", help = "string                  ID of the field to update").flag()
    public val format: Boolean by option("--format", help = "string                    Output format: {json}").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val id: Boolean by option("--id", help = "string                        ID of the item to edit").flag()
    public val iterationId: Boolean by option("--iteration-id", help = "string              ID of the iteration value to set on the field").flag()
    public val jq: Boolean by option("--jq", "-q", help = "expression                    Filter JSON output using a jq expression").flag()
    public val number: Boolean by option("--number", help = "float                     Number value for the field").flag()
    public val owner: Boolean by option("--owner", help = "string                     Login of the owner. Use \"@me\" for the current user.").flag()
    public val projectId: Boolean by option("--project-id", help = "string                ID of the project to which the field belongs to").flag()
    public val singleSelectOptionId: Boolean by option("--single-select-option-id", help = "string   ID of the single select option value to set on the field").flag()
    public val template: Boolean by option("--template", "-t", help = "string                  Format JSON output using a Go template; see \"gh help formatting\"").flag()
    public val text: Boolean by option("--text", help = "string                      Text value for the field").flag()
    public val title: Boolean by option("--title", help = "string                     Title of the draft issue item").flag()
    public val url: Boolean by option("--url", help = "string                       URL of the issue or pull request whose project item to edit").flag()
    public val value: Boolean by option("--value", help = "Value to set on the field named by --field").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                body = body,
                clear = clear,
                date = date,
                field = field,
                fieldId = fieldId,
                format = format,
                help = help,
                id = id,
                iterationId = iterationId,
                jq = jq,
                number = number,
                owner = owner,
                projectId = projectId,
                singleSelectOptionId = singleSelectOptionId,
                template = template,
                text = text,
                title = title,
                url = url,
                value = value,
                version = version
            )
        }
    }
}
