// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class ProjectFieldDeleteCliCommand(
    private val useCase: ProjectFieldDeleteUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "field-delete") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ProjectFieldDeleteUseCase(repository), context)

    override fun help(context: Context): String = "Delete a field in a project"

    public val format: Boolean by option("--format", help = "string     Output format: {json}").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val id: Boolean by option("--id", help = "string         ID of the field to delete").flag()
    public val jq: Boolean by option("--jq", "-q", help = "expression     Filter JSON output using a jq expression").flag()
    public val template: Boolean by option("--template", "-t", help = "string   Format JSON output using a Go template; see \"gh help formatting\"").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                format = format,
                help = help,
                id = id,
                jq = jq,
                template = template,
                version = version
            )
        }
    }
}
