// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class RunDownloadCliCommand(
    private val useCase: RunDownloadUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "download") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(RunDownloadUseCase(repository), context)

    override fun help(context: Context): String = "Download artifacts generated by a GitHub Actions workflow run."

    public val dir: Boolean by option("--dir", "-D", help = "string            The directory to download artifacts into (default \".\")").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val name: Boolean by option("--name", "-n", help = "stringArray      Download artifacts that match any of the given names").flag()
    public val pattern: Boolean by option("--pattern", "-p", help = "stringArray   Download artifacts that match a glob pattern").flag()
    public val repo: Boolean by option("--repo", "-R", help = "[HOST/]OWNER/REPO   Select another repository using the [HOST/]OWNER/REPO format").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                dir = dir,
                help = help,
                name = name,
                pattern = pattern,
                repo = repo,
                version = version
            )
        }
    }
}
