// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class RunViewCliCommand(
    private val useCase: RunViewUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "view") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(RunViewUseCase(repository), context)

    override fun help(context: Context): String = "View a summary of a workflow run."

    public val attempt: Boolean by option("--attempt", "-a", help = "uint      The attempt number of the workflow run").flag()
    public val exitStatus: Boolean by option("--exit-status", help = "Exit with non-zero status if run failed").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val job: Boolean by option("--job", "-j", help = "string        View a specific job ID from a run").flag()
    public val jq: Boolean by option("--jq", "-q", help = "expression     Filter JSON output using a jq expression").flag()
    public val json: Boolean by option("--json", help = "fields       Output JSON with the specified fields").flag()
    public val log: Boolean by option("--log", help = "View full log for either a run or specific job").flag()
    public val logFailed: Boolean by option("--log-failed", help = "View the log for any failed steps in a run or specific job").flag()
    public val repo: Boolean by option("--repo", "-R", help = "[HOST/]OWNER/REPO   Select another repository using the [HOST/]OWNER/REPO format").flag()
    public val template: Boolean by option("--template", "-t", help = "string   Format JSON output using a Go template; see \"gh help formatting\"").flag()
    public val verbose: Boolean by option("--verbose", "-v", help = "Show job steps").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()
    public val web: Boolean by option("--web", "-w", help = "Open run in the browser").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                attempt = attempt,
                exitStatus = exitStatus,
                help = help,
                job = job,
                jq = jq,
                json = json,
                log = log,
                logFailed = logFailed,
                repo = repo,
                template = template,
                verbose = verbose,
                version = version,
                web = web
            )
        }
    }
}
