// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class RunWatchCliCommand(
    private val useCase: RunWatchUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "watch") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(RunWatchUseCase(repository), context)

    override fun help(context: Context): String = "Watch a run until it completes, showing its progress."

    public val compact: Boolean by option("--compact", help = "Show only relevant/failed steps").flag()
    public val exitStatus: Boolean by option("--exit-status", help = "Exit with non-zero status if run fails").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val interval: Boolean by option("--interval", "-i", help = "int   Refresh interval in seconds (default 3)").flag()
    public val repo: Boolean by option("--repo", "-R", help = "[HOST/]OWNER/REPO   Select another repository using the [HOST/]OWNER/REPO format").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                compact = compact,
                exitStatus = exitStatus,
                help = help,
                interval = interval,
                repo = repo,
                version = version
            )
        }
    }
}
