// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class SearchPrsCliCommand(
    private val useCase: SearchPrsUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "prs") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(SearchPrsUseCase(repository), context)

    override fun help(context: Context): String = "Search for pull requests on GitHub."

    public val app: Boolean by option("--app", help = "string              Filter by GitHub App author").flag()
    public val archived: Boolean by option("--archived", help = "Filter based on the repository archived state {true|false}").flag()
    public val assignee: Boolean by option("--assignee", help = "string         Filter by assignee").flag()
    public val author: Boolean by option("--author", help = "string           Filter by author (use --app to filter by a GitHub App)").flag()
    public val base: Boolean by option("--base", "-B", help = "string             Filter on base branch name").flag()
    public val checks: Boolean by option("--checks", help = "string           Filter based on status of the checks: {pending|success|failure}").flag()
    public val closed: Boolean by option("--closed", help = "date             Filter on closed at date").flag()
    public val commenter: Boolean by option("--commenter", help = "user          Filter based on comments by user").flag()
    public val comments: Boolean by option("--comments", help = "number         Filter on number of comments").flag()
    public val created: Boolean by option("--created", help = "date            Filter based on created at date").flag()
    public val draft: Boolean by option("--draft", help = "Filter based on draft state").flag()
    public val head: Boolean by option("--head", "-H", help = "string             Filter on head branch name").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val interactions: Boolean by option("--interactions", help = "number     Filter on number of reactions and comments").flag()
    public val involves: Boolean by option("--involves", help = "user           Filter based on involvement of user").flag()
    public val jq: Boolean by option("--jq", "-q", help = "expression           Filter JSON output using a jq expression").flag()
    public val json: Boolean by option("--json", help = "fields             Output JSON with the specified fields").flag()
    public val label: Boolean by option("--label", help = "strings           Filter on label").flag()
    public val language: Boolean by option("--language", help = "string         Filter based on the coding language").flag()
    public val limit: Boolean by option("--limit", "-L", help = "int               Maximum number of results to fetch (default 30)").flag()
    public val locked: Boolean by option("--locked", help = "Filter on locked conversation status").flag()
    public val match: Boolean by option("--match", help = "strings           Restrict search to specific field of issue: {title|body|comments}").flag()
    public val mentions: Boolean by option("--mentions", help = "user           Filter based on user mentions").flag()
    public val merged: Boolean by option("--merged", help = "Filter based on merged state").flag()
    public val mergedAt: Boolean by option("--merged-at", help = "date          Filter on merged at date").flag()
    public val milestone: Boolean by option("--milestone", help = "title         Filter by milestone title").flag()
    public val noAssignee: Boolean by option("--no-assignee", help = "Filter on missing assignee").flag()
    public val noLabel: Boolean by option("--no-label", help = "Filter on missing label").flag()
    public val noMilestone: Boolean by option("--no-milestone", help = "Filter on missing milestone").flag()
    public val noProject: Boolean by option("--no-project", help = "Filter on missing project").flag()
    public val order: Boolean by option("--order", help = "string            Order of results returned, ignored unless '--sort' flag is specified: {asc|desc} (default \"desc\")").flag()
    public val owner: Boolean by option("--owner", help = "strings           Filter on repository owner").flag()
    public val project: Boolean by option("--project", help = "owner/number    Filter on project board owner/number").flag()
    public val reactions: Boolean by option("--reactions", help = "number        Filter on number of reactions").flag()
    public val repo: Boolean by option("--repo", "-R", help = "OWNER/REPO         Filter on repository, in OWNER/REPO format").flag()
    public val review: Boolean by option("--review", help = "string           Filter based on review status: {none|required|approved|changes_requested}").flag()
    public val reviewRequested: Boolean by option("--review-requested", help = "user   Filter on user or team requested to review").flag()
    public val reviewedBy: Boolean by option("--reviewed-by", help = "user        Filter on user who reviewed").flag()
    public val sort: Boolean by option("--sort", help = "string             Sort fetched results: {comments|reactions|reactions-+1|reactions--1|reactions-smile|reactions-thinking_face|reactions-heart|reactions-tada|interactions|created|updated} (default \"best-match\")").flag()
    public val state: Boolean by option("--state", help = "string            Filter based on state: {open|closed}").flag()
    public val teamMentions: Boolean by option("--team-mentions", help = "string    Filter based on team mentions").flag()
    public val template: Boolean by option("--template", "-t", help = "string         Format JSON output using a Go template; see \"gh help formatting\"").flag()
    public val updated: Boolean by option("--updated", help = "date            Filter on last updated at date").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()
    public val visibility: Boolean by option("--visibility", help = "strings      Filter based on repository visibility: {public|private|internal}").flag()
    public val web: Boolean by option("--web", "-w", help = "Open the search query in the web browser").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                app = app,
                archived = archived,
                assignee = assignee,
                author = author,
                base = base,
                checks = checks,
                closed = closed,
                commenter = commenter,
                comments = comments,
                created = created,
                draft = draft,
                head = head,
                help = help,
                interactions = interactions,
                involves = involves,
                jq = jq,
                json = json,
                label = label,
                language = language,
                limit = limit,
                locked = locked,
                match = match,
                mentions = mentions,
                merged = merged,
                mergedAt = mergedAt,
                milestone = milestone,
                noAssignee = noAssignee,
                noLabel = noLabel,
                noMilestone = noMilestone,
                noProject = noProject,
                order = order,
                owner = owner,
                project = project,
                reactions = reactions,
                repo = repo,
                review = review,
                reviewRequested = reviewRequested,
                reviewedBy = reviewedBy,
                sort = sort,
                state = state,
                teamMentions = teamMentions,
                template = template,
                updated = updated,
                version = version,
                visibility = visibility,
                web = web
            )
        }
    }
}
