// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class SearchCommitsCliCommand(
    private val useCase: SearchCommitsUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "commits") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(SearchCommitsUseCase(repository), context)

    override fun help(context: Context): String = "Search for commits on GitHub."

    public val author: Boolean by option("--author", help = "string            Filter by author").flag()
    public val authorDate: Boolean by option("--author-date", help = "date         Filter based on authored date").flag()
    public val authorEmail: Boolean by option("--author-email", help = "string      Filter on author email").flag()
    public val authorName: Boolean by option("--author-name", help = "string       Filter on author name").flag()
    public val committer: Boolean by option("--committer", help = "string         Filter by committer").flag()
    public val committerDate: Boolean by option("--committer-date", help = "date      Filter based on committed date").flag()
    public val committerEmail: Boolean by option("--committer-email", help = "string   Filter on committer email").flag()
    public val committerName: Boolean by option("--committer-name", help = "string    Filter on committer name").flag()
    public val hash: Boolean by option("--hash", help = "string              Filter by commit hash").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val jq: Boolean by option("--jq", "-q", help = "expression            Filter JSON output using a jq expression").flag()
    public val json: Boolean by option("--json", help = "fields              Output JSON with the specified fields").flag()
    public val limit: Boolean by option("--limit", "-L", help = "int                Maximum number of commits to fetch (default 30)").flag()
    public val merge: Boolean by option("--merge", help = "Filter on merge commits").flag()
    public val order: Boolean by option("--order", help = "string             Order of commits returned, ignored unless '--sort' flag is specified: {asc|desc} (default \"desc\")").flag()
    public val owner: Boolean by option("--owner", help = "strings            Filter on repository owner").flag()
    public val parent: Boolean by option("--parent", help = "string            Filter by parent hash").flag()
    public val repo: Boolean by option("--repo", "-R", help = "OWNER/REPO          Filter on repository, in OWNER/REPO format").flag()
    public val sort: Boolean by option("--sort", help = "string              Sort fetched commits: {author-date|committer-date} (default \"best-match\")").flag()
    public val template: Boolean by option("--template", "-t", help = "string          Format JSON output using a Go template; see \"gh help formatting\"").flag()
    public val tree: Boolean by option("--tree", help = "string              Filter by tree hash").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()
    public val visibility: Boolean by option("--visibility", help = "strings       Filter based on repository visibility: {public|private|internal}").flag()
    public val web: Boolean by option("--web", "-w", help = "Open the search query in the web browser").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                author = author,
                authorDate = authorDate,
                authorEmail = authorEmail,
                authorName = authorName,
                committer = committer,
                committerDate = committerDate,
                committerEmail = committerEmail,
                committerName = committerName,
                hash = hash,
                help = help,
                jq = jq,
                json = json,
                limit = limit,
                merge = merge,
                order = order,
                owner = owner,
                parent = parent,
                repo = repo,
                sort = sort,
                template = template,
                tree = tree,
                version = version,
                visibility = visibility,
                web = web
            )
        }
    }
}
