// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class SkillUpdateCliCommand(
    private val useCase: SkillUpdateUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "update") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(SkillUpdateUseCase(repository), context)

    override fun help(context: Context): String = "Checks installed skills for available updates by comparing the local"

    public val all: Boolean by option("--all", help = "Update all skills without prompting").flag()
    public val dir: Boolean by option("--dir", help = "string   Scan a custom directory for installed skills").flag()
    public val dryRun: Boolean by option("--dry-run", help = "Report available updates without modifying files").flag()
    public val force: Boolean by option("--force", help = "Re-download even if already up to date").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val unpin: Boolean by option("--unpin", help = "Clear pinned version and include pinned skills in update").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                all = all,
                dir = dir,
                dryRun = dryRun,
                force = force,
                help = help,
                unpin = unpin,
                version = version
            )
        }
    }
}
