// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class SkillPreviewCliCommand(
    private val useCase: SkillPreviewUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "preview") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(SkillPreviewUseCase(repository), context)

    override fun help(context: Context): String = "Render a skill's `SKILL.md` content in the terminal. This fetches the"

    public val allowHiddenDirs: Boolean by option("--allow-hidden-dirs", help = "Include skills in hidden directories (e.g. .claude/skills/, .agents/skills/)").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                allowHiddenDirs = allowHiddenDirs,
                help = help,
                version = version
            )
        }
    }
}
