// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class SkillPublishCliCommand(
    private val useCase: SkillPublishUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "publish") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(SkillPublishUseCase(repository), context)

    override fun help(context: Context): String = "Validate a local repository's skills against the Agent Skills specification"

    public val dryRun: Boolean by option("--dry-run", help = "Validate without publishing").flag()
    public val fix: Boolean by option("--fix", help = "Auto-fix issues where possible without publishing (e.g. strip install metadata)").flag()
    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val tag: Boolean by option("--tag", help = "string   Version tag for the release (e.g. v1.0.0)").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                dryRun = dryRun,
                fix = fix,
                help = help,
                tag = tag,
                version = version
            )
        }
    }
}
