// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.gh.*
import java.io.File

public class SshKeyAddCliCommand(
    private val useCase: SshKeyAddUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "add") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(SshKeyAddUseCase(repository), context)

    override fun help(context: Context): String = "Add an SSH key to your GitHub account"

    public val help: Boolean by option("--help", help = "Show help for command").flag()
    public val title: Boolean by option("--title", "-t", help = "string   Title for the new key").flag()
    public val type: Boolean by option("--type", help = "string    Type of the ssh key: {authentication|signing} (default \"authentication\")").flag()
    public val version: Boolean by option("--version", help = "Show gh version").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                title = title,
                type = type,
                version = version
            )
        }
    }
}
