// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.zipalign

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class AlignCommand(
    public val checkOnly: Boolean = false,
    public val overwrite: Boolean = false,
    public val pageAlign: Boolean = false,
    public val pageSizeKb: Int? = null,
    public val verbose: Boolean = false,
    public val zopfli: Boolean = false,
    public val alignment: Int,
    public val infile: File,
    public val outfile: File? = null
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.ZIPALIGN
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)
    override val artifactRequirements: List<ArtifactRequirement> get() = listOf(
        ArtifactRequirement("infile", File(requireNotNull(infile).toString()), ArtifactKind.FILE, ArtifactDirection.INPUT, true),
        ArtifactRequirement("outfile", File(outfile?.toString() ?: ""), ArtifactKind.FILE, ArtifactDirection.OUTPUT, outfile != null)
    )

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        if (checkOnly) args.add("-c")
        if (overwrite) args.add("-f")
        if (pageAlign) args.add("-p")
        pageSizeKb?.let { val value = it
            args.add("-P")
            args.add(value.toString())
        }
        if (verbose) args.add("-v")
        if (zopfli) args.add("-z")
        args.add(alignment.toString())
        args.add(infile.toString())
        outfile?.let { args.add(it.toString()) }
        return args
    }
}
