// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.mkdtboimg

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class CfgCreateUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        dtbDir: Boolean = false,
        help: Boolean = false
    ): Unit {
        val command = CfgCreateCommand(
            dtbDir = dtbDir,
            help = help
        )
        return repository.execute(command, context)
    }
}
