// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.fec.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.fec.*
import java.io.File

public class FecCliCommand(
    private val useCase: ExecuteUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "fec") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ExecuteUseCase(repository), context)

    override fun help(context: Context): String = "Execute the tool with its options and positional operands"

    public val H: Boolean by option("--h", "-h", help = "show this help").flag()
    public val S: Boolean by option("--s", "-S", help = "treat data as a sparse file").flag()
    public val V: Boolean by option("--v", "-v", help = "enable verbose logging").flag()
    public val inplace: Boolean by option("--inplace", "-i", help = "correct <data> in place").flag()
    public val padding: String? by option("--padding", "-p", help = "add padding after ECC data")
    public val roots: String? by option("--roots", "-r", help = "number of parity bytes")
    public val threads: String? by option("--threads", "-j", help = "number of threads to use")
    public val positionalArgs: List<String> by argument(name = "positionalArgs", help = "Tool-specific positional operands").multiple()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                H = H,
                S = S,
                V = V,
                inplace = inplace,
                padding = padding,
                roots = roots,
                threads = threads,
                positionalArgs = positionalArgs
            )
        }
    }
}
