// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.adb.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.core.subcommands
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.adb.*

public class AdbCliCommand(
    private val repository: ToolRepository,
    private val context: ExecutionContext
) : CliktCommand(name = "adb") {

    override fun help(context: Context): String = "CLI entry point for adb"

    init {
        subcommands(
            AttachCliCommand(AttachUseCase(repository), context),
            BugreportCliCommand(BugreportUseCase(repository), context),
            ConnectCliCommand(ConnectUseCase(repository), context),
            DetachCliCommand(DetachUseCase(repository), context),
            DevicesCliCommand(DevicesUseCase(repository), context),
            DisableVerityCliCommand(DisableVerityUseCase(repository), context),
            DisconnectCliCommand(DisconnectUseCase(repository), context),
            EmuCliCommand(EmuUseCase(repository), context),
            EnableVerityCliCommand(EnableVerityUseCase(repository), context),
            ExecOutCliCommand(ExecOutUseCase(repository), context),
            ForwardCliCommand(ForwardUseCase(repository), context),
            GetDevpathCliCommand(GetDevpathUseCase(repository), context),
            GetSerialnoCliCommand(GetSerialnoUseCase(repository), context),
            GetStateCliCommand(GetStateUseCase(repository), context),
            HelpCliCommand(HelpUseCase(repository), context),
            InstallCliCommand(InstallUseCase(repository), context),
            InstallMultiPackageCliCommand(InstallMultiPackageUseCase(repository), context),
            InstallMultipleCliCommand(InstallMultipleUseCase(repository), context),
            JdwpCliCommand(JdwpUseCase(repository), context),
            KeygenCliCommand(KeygenUseCase(repository), context),
            KillServerCliCommand(KillServerUseCase(repository), context),
            LogcatCliCommand(LogcatUseCase(repository), context),
            MdnsCliCommand(MdnsUseCase(repository), context),
            PairCliCommand(PairUseCase(repository), context),
            PullCliCommand(PullUseCase(repository), context),
            PushCliCommand(PushUseCase(repository), context),
            RebootCliCommand(RebootUseCase(repository), context),
            ReconnectCliCommand(ReconnectUseCase(repository), context),
            RemountCliCommand(RemountUseCase(repository), context),
            ReverseCliCommand(ReverseUseCase(repository), context),
            RootCliCommand(RootUseCase(repository), context),
            ShellCliCommand(ShellUseCase(repository), context),
            SideloadCliCommand(SideloadUseCase(repository), context),
            StartServerCliCommand(StartServerUseCase(repository), context),
            SyncCliCommand(SyncUseCase(repository), context),
            TcpipCliCommand(TcpipUseCase(repository), context),
            UninstallCliCommand(UninstallUseCase(repository), context),
            UnrootCliCommand(UnrootUseCase(repository), context),
            UsbCliCommand(UsbUseCase(repository), context),
            VersionCliCommand(VersionUseCase(repository), context),
            WaitForCliCommand(WaitForUseCase(repository), context)
        )
    }

    override fun run() {}
}
