// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.adb.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.adb.*
import java.io.File

public class ShellCliCommand(
    private val useCase: ShellUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "shell") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ShellUseCase(repository), context)

    override fun help(context: Context): String = "run remote shell command"

    public val disableExitSeparation: Boolean by option("--disable-exit-separation", "-x", help = "disable remote exit codes and stdout/stderr separation").flag()
    public val disablePty: Boolean by option("--disable-pty", "-T", help = "disable pty allocation").flag()
    public val escapeChar: String? by option("--escape-char", help = "choose escape character")
    public val exitOnWriteError: Boolean by option("--exit-on-write-error", help = "exit if stdout is closed").flag()
    public val forcePty: Boolean by option("--force-pty", help = "allocate a pty if on a tty").flag()
    public val listenAll: Boolean by option("--listen-all", "-a", help = "listen on all network interfaces, not just localhost").flag()
    public val noStdin: Boolean by option("--no-stdin", "-n", help = "do not read from stdin").flag()
    public val oneDevice: String? by option("--one-device", help = "only allowed with 'start-server' or 'server nodaemon', server will only connect to one USB device, specified by a serial number or USB device address.")
    public val serial: String? by option("--serial", "-s", help = "use device with given serial (overrides &#36;ANDROID_SERIAL)")
    public val serverHost: String? by option("--server-host", "-H", help = "name of adb server host [default=localhost]")
    public val serverPort: Int? by option("--server-port", "-P", help = "port of adb server [default=5037]").int()
    public val serverSocket: String? by option("--server-socket", "-L", help = "listen on given socket for adb server [default=tcp:localhost:5037]")
    public val transportId: String? by option("--transport-id", help = "use device with given transport id")
    public val useTcp: Boolean by option("--use-tcp", help = "use TCP/IP device (error if multiple TCP/IP devices available)").flag()
    public val useUsb: Boolean by option("--use-usb", "-d", help = "use USB device (error if multiple devices connected)").flag()
    public val command: List<String> by argument(name = "command", help = "shell command to run").multiple()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                disableExitSeparation = disableExitSeparation,
                disablePty = disablePty,
                escapeChar = escapeChar,
                exitOnWriteError = exitOnWriteError,
                forcePty = forcePty,
                listenAll = listenAll,
                noStdin = noStdin,
                oneDevice = oneDevice,
                serial = serial,
                serverHost = serverHost,
                serverPort = serverPort,
                serverSocket = serverSocket,
                transportId = transportId,
                useTcp = useTcp,
                useUsb = useUsb,
                command = command
            )
        }
    }
}
