// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.mkfserofs

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class ExecuteCommand(
    public val B: String? = null,
    public val C: String? = null,
    public val D: String? = null,
    public val E: String? = null,
    public val L: String? = null,
    public val T: String? = null,
    public val U: String? = null,
    public val X: String? = null,
    public val Z: String? = null,
    public val allRoot: Boolean = false,
    public val allTime: Boolean = false,
    public val aufs: Boolean = false,
    public val blobdev: String? = null,
    public val blockListFile: String? = null,
    public val chunksize: String? = null,
    public val clean: String? = null,
    public val compressHints: String? = null,
    public val excludePath: String? = null,
    public val excludeRegex: String? = null,
    public val fileContexts: String? = null,
    public val forceGid: String? = null,
    public val forceUid: String? = null,
    public val fsConfigFile: String? = null,
    public val gidOffset: String? = null,
    public val hardDereference: Boolean = false,
    public val help: Boolean = false,
    public val ignoreMtime: Boolean = false,
    public val incremental: String? = null,
    public val maxExtentBytes: String? = null,
    public val mkfsTime: Boolean = false,
    public val mountPoint: String? = null,
    public val offset: String? = null,
    public val ovlfsStrip: String? = null,
    public val preserveMtime: Boolean = false,
    public val productOut: String? = null,
    public val quiet: Boolean = false,
    public val rootXattrIsize: String? = null,
    public val sort: File? = null,
    public val tar: String? = null,
    public val uidOffset: String? = null,
    public val ungzip: String? = null,
    public val unxz: String? = null,
    public val version: Boolean = false,
    public val workers: String? = null,
    public val xattrPrefix: String? = null,
    public val zfeatureBits: String? = null,
    public val positionalArgs: List<String> = emptyList()
) : ToolCommand<String> {

    override val toolId: ToolId get() = ToolId.MKFS_EROFS
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<String> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("identity") as io.ltirom.tooling.core.ToolOutputParser<String>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): String {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        B?.let { val value = it
            args.add("-b")
            args.add(value.toString())
        }
        C?.let { val value = it
            args.add("-C")
            args.add(value.toString())
        }
        D?.let { val value = it
            args.add("-d")
            args.add(value.toString())
        }
        E?.let { val value = it
            args.add("-E")
            args.add(value.toString())
        }
        L?.let { val value = it
            args.add("-L")
            args.add(value.toString())
        }
        T?.let { val value = it
            args.add("-T")
            args.add(value.toString())
        }
        U?.let { val value = it
            args.add("-U")
            args.add(value.toString())
        }
        X?.let { val value = it
            args.add("-x")
            args.add(value.toString())
        }
        Z?.let { val value = it
            args.add("-z")
            args.add(value.toString())
        }
        if (allRoot) args.add("--all-root")
        if (allTime) args.add("--all-time")
        if (aufs) args.add("--aufs")
        blobdev?.let { val value = it
            args.add("--blobdev")
            args.add(value.toString())
        }
        blockListFile?.let { val value = it
            args.add("--block-list-file")
            args.add(value.toString())
        }
        chunksize?.let { val value = it
            args.add("--chunksize")
            args.add(value.toString())
        }
        clean?.let { val value = it
            args.add("--clean")
            args.add(value.toString())
        }
        compressHints?.let { val value = it
            args.add("--compress-hints")
            args.add(value.toString())
        }
        excludePath?.let { val value = it
            args.add("--exclude-path")
            args.add(value.toString())
        }
        excludeRegex?.let { val value = it
            args.add("--exclude-regex")
            args.add(value.toString())
        }
        fileContexts?.let { val value = it
            args.add("--file-contexts")
            args.add(value.toString())
        }
        forceGid?.let { val value = it
            args.add("--force-gid")
            args.add(value.toString())
        }
        forceUid?.let { val value = it
            args.add("--force-uid")
            args.add(value.toString())
        }
        fsConfigFile?.let { val value = it
            args.add("--fs-config-file")
            args.add(value.toString())
        }
        gidOffset?.let { val value = it
            args.add("--gid-offset")
            args.add(value.toString())
        }
        if (hardDereference) args.add("--hard-dereference")
        if (help) args.add("--help")
        if (ignoreMtime) args.add("--ignore-mtime")
        incremental?.let { val value = it
            args.add("--incremental")
            args.add(value.toString())
        }
        maxExtentBytes?.let { val value = it
            args.add("--max-extent-bytes")
            args.add(value.toString())
        }
        if (mkfsTime) args.add("--mkfs-time")
        mountPoint?.let { val value = it
            args.add("--mount-point")
            args.add(value.toString())
        }
        offset?.let { val value = it
            args.add("--offset")
            args.add(value.toString())
        }
        ovlfsStrip?.let { val value = it
            args.add("--ovlfs-strip")
            args.add(value.toString())
        }
        if (preserveMtime) args.add("--preserve-mtime")
        productOut?.let { val value = it
            args.add("--product-out")
            args.add(value.toString())
        }
        if (quiet) args.add("--quiet")
        rootXattrIsize?.let { val value = it
            args.add("--root-xattr-isize")
            args.add(value.toString())
        }
        sort?.let { val value = it
            args.add("--sort")
            args.add(value.toString())
        }
        tar?.let { val value = it
            args.add("--tar")
            args.add(value.toString())
        }
        uidOffset?.let { val value = it
            args.add("--uid-offset")
            args.add(value.toString())
        }
        ungzip?.let { val value = it
            args.add("--ungzip")
            args.add(value.toString())
        }
        unxz?.let { val value = it
            args.add("--unxz")
            args.add(value.toString())
        }
        if (version) args.add("--version")
        workers?.let { val value = it
            args.add("--workers")
            args.add(value.toString())
        }
        xattrPrefix?.let { val value = it
            args.add("--xattr-prefix")
            args.add(value.toString())
        }
        zfeatureBits?.let { val value = it
            args.add("--zfeature-bits")
            args.add(value.toString())
        }
        for (item in positionalArgs) {
            args.add(item.toString())
        }
        return args
    }
}
