package io.ltirom.tooling.codegen.spec

import io.ltirom.tooling.core.ToolRisk
import java.io.File

object KotlinModelGenerator {

    fun generate(spec: ToolSpecification, outputDir: File) {
        val toolPackage = spec.tool.lowercase().replace("-", "").replace(".", "")
        val packageDir = File(outputDir, "io/ltirom/tooling/adapters/$toolPackage")
        packageDir.mkdirs()

        // 1. Generate Choices Enums
        generateEnums(spec, packageDir, toolPackage)

        // 2. Generate Commands & UseCases
        for (cmd in spec.commands.sortedBy { it.name }) {
            generateCommand(spec, cmd, packageDir, toolPackage)
            generateUseCase(spec, cmd, packageDir, toolPackage)
        }
    }

    private fun generateEnums(spec: ToolSpecification, packageDir: File, toolPackage: String) {
        val enums = mutableMapOf<String, List<String>>()

        // Enum names must match every consumer's naming (getKotlinType /
        // getCliktPropertyType prefix with the command name), so global options
        // are emitted per command exactly like command options are.
        for (cmd in spec.commands) {
            val distinctOptions = (spec.globalOptions + cmd.options).distinctBy { it.name }
            for (opt in distinctOptions) {
                if (opt.type == OptionType.CHOICE && opt.choices != null) {
                    enums[cmd.name.capitalize() + opt.name.capitalize() + "Type"] = opt.choices
                }
            }
            for (arg in cmd.arguments) {
                if (arg.type == OptionType.CHOICE && arg.choices != null) {
                    enums[cmd.name.capitalize() + arg.name.capitalize() + "Type"] = arg.choices
                }
            }
        }

        for ((name, choices) in enums.toSortedMap()) {
            val file = File(packageDir, "$name.kt")
            val content = buildString {
                appendLine("// This file is generated by tooling-codegen — do not edit by hand.")
                appendLine("// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.")
                appendLine("package io.ltirom.tooling.adapters.$toolPackage")
                appendLine()
                appendLine("public enum class $name(public val value: String) {")
                for (choice in choices) {
                    val enumName = choice.uppercase().replace("-", "_").replace(".", "_")
                    appendLine("    $enumName(\"$choice\"),")
                }
                appendLine("}")
            }
            file.writeText(content)
        }
    }

    private fun generateCommand(spec: ToolSpecification, cmd: CommandSpec, packageDir: File, toolPackage: String) {
        val className = cmd.name.capitalize() + "Command"
        val file = File(packageDir, "$className.kt")
        
        val content = buildString {
            appendLine("// This file is generated by tooling-codegen — do not edit by hand.")
            appendLine("// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.")
            appendLine("package io.ltirom.tooling.adapters.$toolPackage")
            appendLine()
            appendLine("import io.ltirom.tooling.core.ToolCommand")
            val binaryStdout = spec.tool == "adb" && cmd.name == "execOut"
            if (binaryStdout) appendLine("import io.ltirom.tooling.core.BinaryToolCommand")
            appendLine("import io.ltirom.tooling.core.ToolId")
            appendLine("import io.ltirom.tooling.core.ToolRisk")
            appendLine("import io.ltirom.tooling.core.StdinMode")
            appendLine("import io.ltirom.tooling.core.ArtifactRequirement")
            appendLine("import io.ltirom.tooling.core.ArtifactKind")
            appendLine("import io.ltirom.tooling.core.ArtifactDirection")
            if (spec.tool == "signapk") {
                appendLine("import io.ltirom.tooling.core.SignedArchiveValidator")
                appendLine("import io.ltirom.tooling.core.SignApkInvocation")
            }
            appendLine("import java.io.File")
            appendLine()
            
            appendLine("public data class $className(")
            // Option properties
            val props = mutableListOf<String>()
            val distinctOptions = (spec.globalOptions + cmd.options).distinctBy { it.name }.sortedBy { it.name }
            for (opt in distinctOptions) {
                val kotlinType = getKotlinType(opt.type, opt.choices, cmd.name, opt.name, opt.repeatable)
                val defaultVal = getKotlinDefault(opt.type, opt.default, opt.required, opt.repeatable, if (opt.type == OptionType.CHOICE) kotlinType.removeSuffix("?") else null)
                props.add("    public val ${opt.name}: $kotlinType$defaultVal")
            }
            // Argument properties
            for (arg in cmd.arguments.sortedBy { it.name }) {
                val kotlinType = getKotlinType(arg.type, arg.choices, cmd.name, arg.name, arg.repeatable, arg.required)
                val defaultVal = getKotlinDefault(arg.type, arg.default, arg.required, arg.repeatable, if (arg.type == OptionType.CHOICE) kotlinType.removeSuffix("?") else null)
                props.add("    public val ${arg.name}: $kotlinType$defaultVal")
            }
            appendLine(props.joinToString(",\n"))
            appendLine(") : ${if (binaryStdout) "BinaryToolCommand<${cmd.outputType}>" else "ToolCommand<${cmd.outputType}>"} {")
            appendLine()
            
            val toolIdConstant = spec.tool.uppercase().replace("-", "_").replace(".", "_")
            val cmdRisk = cmd.risk ?: spec.risk ?: io.ltirom.tooling.core.ToolRisk.READ_ONLY
            appendLine("    override val toolId: ToolId get() = ToolId.$toolIdConstant")
            appendLine("    override val risk: ToolRisk get() = ToolRisk.$cmdRisk")
            appendLine("    override val stdinMode: StdinMode get() = StdinMode.EMPTY")
            appendLine("    override val stdinText: String? get() = null")
            val acceptedExitCodes = spec.exitCodes.filter { it.isSuccess }.map { it.code }.ifEmpty { listOf(0) }
            appendLine("    override val acceptedExitCodes: Set<Int> get() = setOf(${acceptedExitCodes.joinToString()})")
            if (cmd.artifacts.isNotEmpty()) {
                appendLine("    override val artifactRequirements: List<ArtifactRequirement> get() = listOf(")
                appendLine(cmd.artifacts.joinToString(",\n") { artifact ->
                    val source = if (artifact.index != null) {
                        "${artifact.parameter}.getOrNull(${artifact.index})"
                    } else {
                        artifact.parameter
                    }
                    val path = if (artifact.required) {
                        "File(requireNotNull($source).toString())"
                    } else {
                        "File($source?.toString() ?: \"\")"
                    }
                    val required = if (!artifact.required && artifact.direction == ArtifactDirection.OUTPUT) {
                        "$source != null"
                    } else {
                        artifact.required.toString()
                    }
                    "        ArtifactRequirement(\"${artifact.name}\", $path, ArtifactKind.${artifact.type}, ArtifactDirection.${artifact.direction}, $required)"
                })
                appendLine("    )")
            }
            if (spec.tool == "signapk" && cmd.name == "execute") {
                appendLine("    override fun validateInputArtifacts() {")
                appendLine("        val offset = if (positionalArgs.firstOrNull() == \"-w\") 1 else 0")
                appendLine("        require(positionalArgs.size >= offset + 4) { \"SignApk requires public key, private key, input, and output arguments\" }")
                appendLine("        SignedArchiveValidator.validateInvocation(SignApkInvocation(File(positionalArgs[offset]), File(positionalArgs[offset + 1]), File(positionalArgs[offset + 2]), File(positionalArgs[offset + 3])))")
                appendLine("    }")
            }
            appendLine()
            
            if (binaryStdout) {
                appendLine("    override fun parseBinaryResult(stdout: ByteArray, stderr: String): ByteArray = stdout")
            } else {
                val optionParserName = spec.outputParser ?: cmd.outputParser
                val parserId = optionParserName ?: "default"
                appendLine("    @Suppress(\"UNCHECKED_CAST\")")
                appendLine("    public val parser: io.ltirom.tooling.core.ToolOutputParser<${cmd.outputType}> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get(\"$parserId\") as io.ltirom.tooling.core.ToolOutputParser<${cmd.outputType}>")
                appendLine()
                appendLine("    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): ${cmd.outputType} {")
                appendLine("        return parser.parse(result.stdout, result.stderr)")
                appendLine("    }")
            }
            
            appendLine("    override fun getArguments(): List<String> {")
            appendLine("        val args = mutableListOf<String>()")
            // Append subcommand path
            for (part in cmd.subcommandPath) {
                if (part != "_self") {
                    appendLine("        args.add(\"$part\")")
                }
            }
            // Append options
            for (opt in distinctOptions) {
                val isRepeatable = opt.repeatable
                val isBoolean = opt.type == OptionType.BOOLEAN
                val spelling = opt.spelling
                
                if (isBoolean) {
                    appendLine("        if (${opt.name}) args.add(\"$spelling\")")
                } else if (isRepeatable) {
                    appendLine("        for (item in ${opt.name}) {")
                    if (spelling.endsWith("=")) {
                        appendLine("            args.add(\"$spelling\$item\")")
                    } else {
                        appendLine("            args.add(\"$spelling\")")
                        appendLine("            args.add(item.toString())")
                    }
                    appendLine("        }")
                } else {
                    appendLine("        ${opt.name}?.let { val value = it")
                    if (spelling.endsWith("=")) {
                        appendLine("            args.add(\"$spelling\$value\")")
                    } else {
                        appendLine("            args.add(\"$spelling\")")
                        if (opt.type == OptionType.CHOICE) {
                            appendLine("            args.add(value.value)")
                        } else {
                            appendLine("            args.add(value.toString())")
                        }
                    }
                    appendLine("        }")
                }
            }
            // Append arguments
            for (arg in cmd.arguments) {
                val isRepeatable = arg.repeatable
                if (isRepeatable) {
                    appendLine("        for (item in ${arg.name}) {")
                    appendLine("            args.add(item.toString())")
                    appendLine("        }")
                } else {
                    if (arg.required) {
                        if (arg.type == OptionType.CHOICE) {
                            appendLine("        args.add(${arg.name}.value)")
                        } else {
                            appendLine("        args.add(${arg.name}.toString())")
                        }
                    } else {
                        appendLine("        ${arg.name}?.let { args.add(it.toString()) }")
                    }
                }
            }
            appendLine("        return args")
            appendLine("    }")
            appendLine("}")
        }
        file.writeText(content)
    }

    private fun generateUseCase(spec: ToolSpecification, cmd: CommandSpec, packageDir: File, toolPackage: String) {
        val useCaseName = cmd.name.capitalize() + "UseCase"
        val commandName = cmd.name.capitalize() + "Command"
        val file = File(packageDir, "$useCaseName.kt")
        
        val distinctOptions = (spec.globalOptions + cmd.options).distinctBy { it.name }.sortedBy { it.name }
        val params = mutableListOf<String>()
        params.add("context: ExecutionContext")
        for (opt in distinctOptions) {
            val kotlinType = getKotlinType(opt.type, opt.choices, cmd.name, opt.name, opt.repeatable)
            val defaultVal = getKotlinDefault(opt.type, opt.default, opt.required, opt.repeatable, if (opt.type == OptionType.CHOICE) kotlinType.removeSuffix("?") else null)
            params.add("${opt.name}: $kotlinType$defaultVal")
        }
        for (arg in cmd.arguments.sortedBy { it.name }) {
            val kotlinType = getKotlinType(arg.type, arg.choices, cmd.name, arg.name, arg.repeatable, arg.required)
            val defaultVal = getKotlinDefault(arg.type, arg.default, arg.required, arg.repeatable, if (arg.type == OptionType.CHOICE) kotlinType.removeSuffix("?") else null)
            params.add("${arg.name}: $kotlinType$defaultVal")
        }
        
        val callArgs = mutableListOf<String>()
        for (opt in distinctOptions) {
            callArgs.add("${opt.name} = ${opt.name}")
        }
        for (arg in cmd.arguments.sortedBy { it.name }) {
            callArgs.add("${arg.name} = ${arg.name}")
        }

        val content = buildString {
            appendLine("// This file is generated by tooling-codegen — do not edit by hand.")
            appendLine("// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.")
            appendLine("package io.ltirom.tooling.adapters.$toolPackage")
            appendLine()
            appendLine("import io.ltirom.tooling.core.ToolRepository")
            appendLine("import io.ltirom.tooling.core.ExecutionContext")
            appendLine("import java.io.File")
            appendLine()
            appendLine("public class $useCaseName(private val repository: ToolRepository) {")
            appendLine()
            appendLine("    public suspend fun execute(")
            appendLine(params.joinToString(",\n        ", prefix = "        "))
            appendLine("    ): ${cmd.outputType} {")
            appendLine("        val command = $commandName(")
            appendLine(callArgs.joinToString(",\n            ", prefix = "            "))
            appendLine("        )")
            appendLine("        return repository.execute(command, context)")
            appendLine("    }")
            appendLine("}")
        }
        file.writeText(content)
    }

    private fun getKotlinType(
        type: OptionType,
        choices: List<String>?,
        cmdName: String,
        optName: String,
        repeatable: Boolean,
        required: Boolean = false
    ): String {
        val base = when (type) {
            OptionType.BOOLEAN -> "Boolean"
            OptionType.STRING -> "String"
            OptionType.INT -> "Int"
            OptionType.PATH -> "File"
            OptionType.CHOICE -> {
                if (choices != null) {
                    cmdName.capitalize() + optName.capitalize() + "Type"
                } else {
                    "String"
                }
            }
        }
        
        return if (repeatable) {
            "List<$base>"
        } else if (type == OptionType.BOOLEAN) {
            "Boolean"
        } else if (required) {
            base
        } else {
            "$base?"
        }
    }

    private fun getKotlinDefault(
        type: OptionType,
        default: String?,
        required: Boolean,
        repeatable: Boolean,
        enumTypeName: String? = null
    ): String {
        if (repeatable) return " = emptyList()"
        if (type == OptionType.BOOLEAN) return " = false"
        if (default != null) {
            if (type == OptionType.STRING) return " = \"$default\""
            if (type == OptionType.INT) return " = $default"
            if (type == OptionType.CHOICE) {
                val enumVal = default.uppercase().replace("-", "_").replace(".", "_")
                val qualified = enumTypeName?.let { "$it.$enumVal" } ?: enumVal
                return " = $qualified"
            }
        }
        return if (required) "" else " = null"
    }
}
private fun String.capitalize() = replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
