// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.img2simg

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ExecuteUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        positionalArgs: List<String> = emptyList()
    ): String {
        val command = ExecuteCommand(
            positionalArgs = positionalArgs
        )
        return repository.execute(command, context)
    }
}
