// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.lpmake

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class ExecuteCommand(
    public val alignment: String? = null,
    public val alignmentOffset: String? = null,
    public val autoSlotSuffixing: Boolean = false,
    public val blockSize: String? = null,
    public val device: String? = null,
    public val deviceSize: String? = null,
    public val forceFullImage: Boolean = false,
    public val group: String? = null,
    public val image: File? = null,
    public val metadataSize: String? = null,
    public val metadataSlots: String? = null,
    public val output: File? = null,
    public val partition: List<String> = emptyList(),
    public val sparse: Boolean = false,
    public val superName: String? = null,
    public val virtualAb: Boolean = false,
    public val positionalArgs: List<String> = emptyList()
) : ToolCommand<String> {

    override val toolId: ToolId get() = ToolId.LPMAKE
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)
    override val artifactRequirements: List<ArtifactRequirement> get() = listOf(
        ArtifactRequirement("outputImage", File(requireNotNull(output).toString()), ArtifactKind.FILE, ArtifactDirection.OUTPUT, true)
    )

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<String> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("identity") as io.ltirom.tooling.core.ToolOutputParser<String>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): String {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        alignment?.let { val value = it
            args.add("--alignment")
            args.add(value.toString())
        }
        alignmentOffset?.let { val value = it
            args.add("--alignment-offset")
            args.add(value.toString())
        }
        if (autoSlotSuffixing) args.add("--auto-slot-suffixing")
        blockSize?.let { val value = it
            args.add("--block-size")
            args.add(value.toString())
        }
        device?.let { val value = it
            args.add("--device")
            args.add(value.toString())
        }
        deviceSize?.let { val value = it
            args.add("--device-size")
            args.add(value.toString())
        }
        if (forceFullImage) args.add("--force-full-image")
        group?.let { val value = it
            args.add("--group")
            args.add(value.toString())
        }
        image?.let { val value = it
            args.add("--image")
            args.add(value.toString())
        }
        metadataSize?.let { val value = it
            args.add("--metadata-size")
            args.add(value.toString())
        }
        metadataSlots?.let { val value = it
            args.add("--metadata-slots")
            args.add(value.toString())
        }
        output?.let { val value = it
            args.add("--output")
            args.add(value.toString())
        }
        for (item in partition) {
            args.add("--partition")
            args.add(item.toString())
        }
        if (sparse) args.add("--sparse")
        superName?.let { val value = it
            args.add("--super-name")
            args.add(value.toString())
        }
        if (virtualAb) args.add("--virtual-ab")
        for (item in positionalArgs) {
            args.add(item.toString())
        }
        return args
    }
}
