// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.fastboot.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.fastboot.*
import java.io.File

public class GsiCliCommand(
    private val useCase: GsiUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "gsi") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(GsiUseCase(repository), context)

    override fun help(context: Context): String = "manage GSI installation"

    public val disableFastbootInfo: Boolean by option("--disable-fastboot-info", help = "Will collects tasks from image list rather than fastboot-info.").flag()
    public val disableSuperOptimization: Boolean by option("--disable-super-optimization", help = "Disables optimizations on flashing super partition.").flag()
    public val disableVerification: Boolean by option("--disable-verification", help = "Sets disable-verification when flashing vbmeta.").flag()
    public val disableVerity: Boolean by option("--disable-verity", help = "Sets disable-verity when flashing vbmeta.").flag()
    public val excludeDynamicPartitions: Boolean by option("--exclude-dynamic-partitions", help = "Excludes flashing of dynamic partitions.").flag()
    public val forceOperation: Boolean by option("--force", help = "Force a flash operation that may be unsafe.").flag()
    public val fsOptions: String? by option("--fs-options", help = "Enable filesystem features. OPTION supports casefold, projid, compress")
    public val selectDevice: String? by option("--select-device", "-s", help = "Specify a USB device.")
    public val setActiveSlot: String? by option("--set-active", help = "Sets the active slot before rebooting.")
    public val skipReboot: Boolean by option("--skip-reboot", help = "Don't reboot device after flashing.").flag()
    public val skipSecondarySlots: Boolean by option("--skip-secondary", help = "Don't flash secondary slots in flashall/update.").flag()
    public val slotTarget: String? by option("--slot", help = "Use SLOT; 'all' for both slots, 'other' for the other slot.")
    public val sparseSize: String? by option("--sparse-size", "-S", help = "break into sparse files no larger than SIZE")
    public val unbufferedOutput: Boolean by option("--unbuffered", help = "Don't buffer input or output.").flag()
    public val verboseMode: Boolean by option("--verbose", "-v", help = "Verbose output.").flag()
    public val wipeUserdata: Boolean by option("--wipe-userdata", "-w", help = "Wipe userdata.").flag()
    public val args: List<String> by argument(name = "args", help = "GSI arguments").multiple()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                disableFastbootInfo = disableFastbootInfo,
                disableSuperOptimization = disableSuperOptimization,
                disableVerification = disableVerification,
                disableVerity = disableVerity,
                excludeDynamicPartitions = excludeDynamicPartitions,
                forceOperation = forceOperation,
                fsOptions = fsOptions,
                selectDevice = selectDevice,
                setActiveSlot = setActiveSlot,
                skipReboot = skipReboot,
                skipSecondarySlots = skipSecondarySlots,
                slotTarget = slotTarget,
                sparseSize = sparseSize,
                unbufferedOutput = unbufferedOutput,
                verboseMode = verboseMode,
                wipeUserdata = wipeUserdata,
                args = args
            )
        }
    }
}
