// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.aapt2.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.core.subcommands
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.aapt2.*

public class Aapt2CliCommand(
    private val repository: ToolRepository,
    private val context: ExecutionContext
) : CliktCommand(name = "aapt2") {

    override fun help(context: Context): String = "CLI entry point for aapt2"

    init {
        subcommands(
            ApkinfoCliCommand(ApkinfoUseCase(repository), context),
            CompileCliCommand(CompileUseCase(repository), context),
            ConvertCliCommand(ConvertUseCase(repository), context),
            DaemonCliCommand(DaemonUseCase(repository), context),
            DiffCliCommand(DiffUseCase(repository), context),
            DumpCliCommand(DumpUseCase(repository), context),
            DumpApcCliCommand(DumpApcUseCase(repository), context),
            DumpBadgingCliCommand(DumpBadgingUseCase(repository), context),
            DumpChunksCliCommand(DumpChunksUseCase(repository), context),
            DumpConfigurationsCliCommand(DumpConfigurationsUseCase(repository), context),
            DumpOverlayableCliCommand(DumpOverlayableUseCase(repository), context),
            DumpPackagenameCliCommand(DumpPackagenameUseCase(repository), context),
            DumpPermissionsCliCommand(DumpPermissionsUseCase(repository), context),
            DumpResourcesCliCommand(DumpResourcesUseCase(repository), context),
            DumpStringsCliCommand(DumpStringsUseCase(repository), context),
            DumpStyleparentsCliCommand(DumpStyleparentsUseCase(repository), context),
            DumpXmlstringsCliCommand(DumpXmlstringsUseCase(repository), context),
            DumpXmltreeCliCommand(DumpXmltreeUseCase(repository), context),
            LinkCliCommand(LinkUseCase(repository), context),
            OptimizeCliCommand(OptimizeUseCase(repository), context),
            VersionCliCommand(VersionUseCase(repository), context)
        )
    }

    override fun run() {}
}
