// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.aapt2.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.aapt2.*
import java.io.File

public class CompileCliCommand(
    private val useCase: CompileUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "compile") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(CompileUseCase(repository), context)

    override fun help(context: Context): String = "aapt2 compile [options] -o arg files..."

    public val O: Boolean by option("--o", "-o", help = "arg                                            Output path").flag()
    public val V: Boolean by option("--v", "-v", help = "Enables verbose logging").flag()
    public val dir: Boolean by option("--dir", help = "arg                                         Directory to scan for resources").flag()
    public val featureFlags: Boolean by option("--feature-flags", help = "arg                               Specify the values of feature flags. The pairs in the argument").flag()
    public val filterProduct: Boolean by option("--filter-product", help = "arg                              Leave only resources specific to the given product. All other resources (including defaults) are removed.").flag()
    public val help: Boolean by option("--help", help = "Displays this help menu").flag()
    public val legacy: Boolean by option("--legacy", help = "Treat errors that used to be valid in AAPT as warnings").flag()
    public val noCrunch: Boolean by option("--no-crunch", help = "Disables PNG processing").flag()
    public val outputTextSymbols: Boolean by option("--output-text-symbols", help = "arg                         Generates a text file containing the resource symbols in the").flag()
    public val pngCompressionLevel: Boolean by option("--png-compression-level", help = "arg                       Set the zlib compression level for crunched PNG images, [0-9], 9 by default.").flag()
    public val preserveVisibilityOfStyleables: Boolean by option("--preserve-visibility-of-styleables", help = "If specified, apply the same visibility rules for").flag()
    public val pseudoLocalize: Boolean by option("--pseudo-localize", help = "Generate resources for pseudo-locales (en-XA and ar-XB)").flag()
    public val pseudoLocalizeGenderRatio: Boolean by option("--pseudo-localize-gender-ratio", help = "arg                Sets the ratio of resources to generate grammatical gender strings for. The ratio has to be a float number between 0 and 1.").flag()
    public val pseudoLocalizeGenderValues: Boolean by option("--pseudo-localize-gender-values", help = "arg               Sets the gender values to pick up for generating grammatical gender strings, gender values should be f, m, or n, which are shortcuts for feminine, masculine and neuter, and split with comma.").flag()
    public val sourcePath: Boolean by option("--source-path", help = "arg                                 Sets the compiled resource file source file path to the given string.").flag()
    public val traceFolder: Boolean by option("--trace-folder", help = "arg                                Generate systrace json trace fragment to specified folder.").flag()
    public val visibility: Boolean by option("--visibility", help = "arg                                  Sets the visibility of the compiled resources to the specified").flag()
    public val zip: Boolean by option("--zip", help = "arg                                         Zip file containing the res directory to scan for resources").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                O = O,
                V = V,
                dir = dir,
                featureFlags = featureFlags,
                filterProduct = filterProduct,
                help = help,
                legacy = legacy,
                noCrunch = noCrunch,
                outputTextSymbols = outputTextSymbols,
                pngCompressionLevel = pngCompressionLevel,
                preserveVisibilityOfStyleables = preserveVisibilityOfStyleables,
                pseudoLocalize = pseudoLocalize,
                pseudoLocalizeGenderRatio = pseudoLocalizeGenderRatio,
                pseudoLocalizeGenderValues = pseudoLocalizeGenderValues,
                sourcePath = sourcePath,
                traceFolder = traceFolder,
                visibility = visibility,
                zip = zip
            )
        }
    }
}
