// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.aapt2.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.aapt2.*
import java.io.File

public class DumpApcCliCommand(
    private val useCase: DumpApcUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "apc") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(DumpApcUseCase(repository), context)

    override fun help(context: Context): String = "dump apc [options] files..."

    public val V: Boolean by option("--v", "-v", help = "Enables verbose logging.").flag()
    public val help: Boolean by option("--help", help = "Displays this help menu").flag()
    public val noValues: Boolean by option("--no-values", help = "Suppresses output of values when displaying resource tables.").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                V = V,
                help = help,
                noValues = noValues
            )
        }
    }
}
