// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.aapt2.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.aapt2.*
import java.io.File

public class DumpXmlstringsCliCommand(
    private val useCase: DumpXmlstringsUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "xmlstrings") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(DumpXmlstringsUseCase(repository), context)

    override fun help(context: Context): String = "dump xmlstrings [options] --file arg files..."

    public val file: Boolean by option("--file", help = "arg                                        A compiled xml file to print").flag()
    public val help: Boolean by option("--help", help = "Displays this help menu").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                file = file,
                help = help
            )
        }
    }
}
