// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.aapt2.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.aapt2.*
import java.io.File

public class LinkCliCommand(
    private val useCase: LinkUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "link") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(LinkUseCase(repository), context)

    override fun help(context: Context): String = "aapt2 link [options] -o arg --manifest arg files..."

    public val A: Boolean by option("--a", "-A", help = "arg                                            An assets directory to include in the APK. These are unprocessed.").flag()
    public val C: Boolean by option("--c", "-c", help = "arg                                            Comma separated list of configurations to include. The default").flag()
    public val E: Boolean by option("--e", "-e", help = "arg                                            File containing list of extensions not to compress.").flag()
    public val I: Boolean by option("--i", "-I", help = "arg                                            Adds an Android APK to link against.").flag()
    public val O: Boolean by option("--o", "-o", help = "arg                                            Output path.").flag()
    public val R: Boolean by option("--r", "-R", help = "arg                                            Compilation unit to link, using `overlay` semantics.").flag()
    public val V: Boolean by option("--v", "-v", help = "Enables verbose logging.").flag()
    public val X: Boolean by option("--x", "-x", help = "Legacy flag that specifies to use the package identifier 0x01.").flag()
    public val Z: Boolean by option("--z", "-z", help = "Require localization of strings marked 'suggested'.").flag()
    public val addJavadocAnnotation: Boolean by option("--add-javadoc-annotation", help = "arg                      Adds a JavaDoc annotation to all generated Java classes.").flag()
    public val allowReservedPackageId: Boolean by option("--allow-reserved-package-id", help = "Allows the use of a reserved package ID. This should on be used for").flag()
    public val autoAddOverlay: Boolean by option("--auto-add-overlay", help = "Allows the addition of new resources in overlays without").flag()
    public val compileSdkVersionCode: Boolean by option("--compile-sdk-version-code", help = "arg                    Version code (integer) to inject into the AndroidManifest.xml if none is").flag()
    public val compileSdkVersionName: Boolean by option("--compile-sdk-version-name", help = "arg                    Version name to inject into the AndroidManifest.xml if none is present.").flag()
    public val customPackage: Boolean by option("--custom-package", help = "arg                              Custom Java package under which to generate R.java.").flag()
    public val debugMode: Boolean by option("--debug-mode", help = "Inserts android:debuggable=\"true\" in to the application node of the").flag()
    public val emitIds: Boolean by option("--emit-ids", help = "arg                                    Emit a file at the given path with a list of name to ID mappings,").flag()
    public val enableCompactEntries: Boolean by option("--enable-compact-entries", help = "This decreases APK size by using compact resource entries for simple data types.").flag()
    public val enableSparseEncoding: Boolean by option("--enable-sparse-encoding", help = "Enables encoding sparse entries using a binary search tree.").flag()
    public val excludeConfigs: Boolean by option("--exclude-configs", help = "arg                             Excludes values of resources whose configs contain the specified qualifiers.").flag()
    public val excludeSources: Boolean by option("--exclude-sources", help = "Do not serialize source file information when generating resources in").flag()
    public val extraPackages: Boolean by option("--extra-packages", help = "arg                              Generate the same R.java but with different package names.").flag()
    public val featureFlags: Boolean by option("--feature-flags", help = "arg                               Specify the values of feature flags. The pairs in the argument").flag()
    public val fingerprintPrefix: Boolean by option("--fingerprint-prefix", help = "arg                          Fingerprint prefix to add to install constraints.").flag()
    public val help: Boolean by option("--help", help = "Displays this help menu").flag()
    public val java: Boolean by option("--java", help = "arg                                        Directory in which to generate R.java.").flag()
    public val keepRawValues: Boolean by option("--keep-raw-values", help = "Preserve raw attribute values in xml files.").flag()
    public val manifest: Boolean by option("--manifest", help = "arg                                    Path to the Android manifest to build.").flag()
    public val mergeOnly: Boolean by option("--merge-only", help = "Only merge the resources, without verifying resource references. This flag").flag()
    public val minSdkVersion: Boolean by option("--min-sdk-version", help = "arg                             Default minimum SDK version to use for AndroidManifest.xml.").flag()
    public val noAutoVersion: Boolean by option("--no-auto-version", help = "Disables automatic style and layout SDK versioning.").flag()
    public val noCompileSdkMetadata: Boolean by option("--no-compile-sdk-metadata", help = "Suppresses output of compile SDK-related attributes in AndroidManifest.xml,").flag()
    public val noCompress: Boolean by option("--no-compress", help = "Do not compress any resources.").flag()
    public val noCompressFonts: Boolean by option("--no-compress-fonts", help = "Do not compress files with common extensions for fonts.").flag()
    public val noCompressRegex: Boolean by option("--no-compress-regex", help = "arg                           Do not compress extensions matching the regular expression. Remember to").flag()
    public val noProguardLocationReference: Boolean by option("--no-proguard-location-reference", help = "Keep proguard rules files from having a reference to the source file").flag()
    public val noResourceDeduping: Boolean by option("--no-resource-deduping", help = "Disables automatic deduping of resources with").flag()
    public val noResourceRemoval: Boolean by option("--no-resource-removal", help = "Disables automatic removal of resources without").flag()
    public val noStaticLibPackages: Boolean by option("--no-static-lib-packages", help = "Merge all library resources under the app's package.").flag()
    public val noVersionTransitions: Boolean by option("--no-version-transitions", help = "Disables automatic versioning of transition resources. Use this only").flag()
    public val noVersionVectors: Boolean by option("--no-version-vectors", help = "Disables automatic versioning of vector drawables. Use this only").flag()
    public val noXmlNamespaces: Boolean by option("--no-xml-namespaces", help = "Removes XML namespace prefix and URI information").flag()
    public val nonFinalIds: Boolean by option("--non-final-ids", help = "Generates R.java without the final modifier. This is implied when").flag()
    public val nonUpdatableSystem: Boolean by option("--non-updatable-system", help = "Mark the app as a non-updatable system app. This inserts").flag()
    public val outputTextSymbols: Boolean by option("--output-text-symbols", help = "arg                         Generates a text file containing the resource symbols of the R class in").flag()
    public val outputToDir: Boolean by option("--output-to-dir", help = "Outputs the APK contents to a directory specified by -o.").flag()
    public val overrideStylesInsteadOfOverlaying: Boolean by option("--override-styles-instead-of-overlaying", help = "Causes styles defined in -R resources to replace previous definitions").flag()
    public val packageId: Boolean by option("--package-id", help = "arg                                  Specify the package ID to use for this app. Must be greater or equal to").flag()
    public val preferredDensity: Boolean by option("--preferred-density", help = "arg                           Selects the closest matching density and strips out all others.").flag()
    public val privateSymbols: Boolean by option("--private-symbols", help = "arg                             Package name to use when generating R.java for private symbols.").flag()
    public val product: Boolean by option("--product", help = "arg                                     Comma separated list of product names to keep").flag()
    public val proguard: Boolean by option("--proguard", help = "arg                                    Output file for generated Proguard rules.").flag()
    public val proguardConditionalKeepRules: Boolean by option("--proguard-conditional-keep-rules", help = "Generate conditional Proguard keep rules.").flag()
    public val proguardMainDex: Boolean by option("--proguard-main-dex", help = "arg                           Output file for generated Proguard rules for the main dex.").flag()
    public val proguardMinimalKeepRules: Boolean by option("--proguard-minimal-keep-rules", help = "Generate a minimal set of Proguard keep rules.").flag()
    public val protoFormat: Boolean by option("--proto-format", help = "Generates compiled resources in Protobuf format.").flag()
    public val renameInstrumentationTargetPackage: Boolean by option("--rename-instrumentation-target-package", help = "arg       Changes the name of the target package for instrumentation. Most useful").flag()
    public val renameManifestPackage: Boolean by option("--rename-manifest-package", help = "arg                     Renames the package in AndroidManifest.xml.").flag()
    public val renameOverlayCategory: Boolean by option("--rename-overlay-category", help = "arg                     Changes the category for the overlay.").flag()
    public val renameOverlayTargetPackage: Boolean by option("--rename-overlay-target-package", help = "arg               Changes the name of the target package for overlay. Most useful").flag()
    public val renameResourcesPackage: Boolean by option("--rename-resources-package", help = "arg                    Renames the package in resources table").flag()
    public val replaceVersion: Boolean by option("--replace-version", help = "If --version-code, --version-name, and/or --revision-code are specified, these").flag()
    public val revisionCode: Boolean by option("--revision-code", help = "arg                               Revision code (integer) to inject into the AndroidManifest.xml if none is").flag()
    public val sharedLib: Boolean by option("--shared-lib", help = "Generates a shared Android runtime library.").flag()
    public val split: Boolean by option("--split", help = "arg                                       Split resources matching a set of configs out to a Split APK.").flag()
    public val stableIds: Boolean by option("--stable-ids", help = "arg                                  File containing a list of name to ID mapping.").flag()
    public val staticLib: Boolean by option("--static-lib", help = "Generate a static Android library.").flag()
    public val strictVisibility: Boolean by option("--strict-visibility", help = "Do not allow overlays with different visibility levels.").flag()
    public val targetSdkVersion: Boolean by option("--target-sdk-version", help = "arg                          Default target SDK version to use for AndroidManifest.xml.").flag()
    public val traceFolder: Boolean by option("--trace-folder", help = "arg                                Generate systrace json trace fragment to specified folder.").flag()
    public val value0: Boolean by option("--value0", "-0", help = "arg                                            File suffix not to compress.").flag()
    public val versionCode: Boolean by option("--version-code", help = "arg                                Version code (integer) to inject into the AndroidManifest.xml if none is").flag()
    public val versionCodeMajor: Boolean by option("--version-code-major", help = "arg                          Version code major (integer) to inject into the AndroidManifest.xml if none is").flag()
    public val versionName: Boolean by option("--version-name", help = "arg                                Version name to inject into the AndroidManifest.xml if none is present.").flag()
    public val warnManifestValidation: Boolean by option("--warn-manifest-validation", help = "Treat manifest validation errors as warnings.").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                A = A,
                C = C,
                E = E,
                I = I,
                O = O,
                R = R,
                V = V,
                X = X,
                Z = Z,
                addJavadocAnnotation = addJavadocAnnotation,
                allowReservedPackageId = allowReservedPackageId,
                autoAddOverlay = autoAddOverlay,
                compileSdkVersionCode = compileSdkVersionCode,
                compileSdkVersionName = compileSdkVersionName,
                customPackage = customPackage,
                debugMode = debugMode,
                emitIds = emitIds,
                enableCompactEntries = enableCompactEntries,
                enableSparseEncoding = enableSparseEncoding,
                excludeConfigs = excludeConfigs,
                excludeSources = excludeSources,
                extraPackages = extraPackages,
                featureFlags = featureFlags,
                fingerprintPrefix = fingerprintPrefix,
                help = help,
                java = java,
                keepRawValues = keepRawValues,
                manifest = manifest,
                mergeOnly = mergeOnly,
                minSdkVersion = minSdkVersion,
                noAutoVersion = noAutoVersion,
                noCompileSdkMetadata = noCompileSdkMetadata,
                noCompress = noCompress,
                noCompressFonts = noCompressFonts,
                noCompressRegex = noCompressRegex,
                noProguardLocationReference = noProguardLocationReference,
                noResourceDeduping = noResourceDeduping,
                noResourceRemoval = noResourceRemoval,
                noStaticLibPackages = noStaticLibPackages,
                noVersionTransitions = noVersionTransitions,
                noVersionVectors = noVersionVectors,
                noXmlNamespaces = noXmlNamespaces,
                nonFinalIds = nonFinalIds,
                nonUpdatableSystem = nonUpdatableSystem,
                outputTextSymbols = outputTextSymbols,
                outputToDir = outputToDir,
                overrideStylesInsteadOfOverlaying = overrideStylesInsteadOfOverlaying,
                packageId = packageId,
                preferredDensity = preferredDensity,
                privateSymbols = privateSymbols,
                product = product,
                proguard = proguard,
                proguardConditionalKeepRules = proguardConditionalKeepRules,
                proguardMainDex = proguardMainDex,
                proguardMinimalKeepRules = proguardMinimalKeepRules,
                protoFormat = protoFormat,
                renameInstrumentationTargetPackage = renameInstrumentationTargetPackage,
                renameManifestPackage = renameManifestPackage,
                renameOverlayCategory = renameOverlayCategory,
                renameOverlayTargetPackage = renameOverlayTargetPackage,
                renameResourcesPackage = renameResourcesPackage,
                replaceVersion = replaceVersion,
                revisionCode = revisionCode,
                sharedLib = sharedLib,
                split = split,
                stableIds = stableIds,
                staticLib = staticLib,
                strictVisibility = strictVisibility,
                targetSdkVersion = targetSdkVersion,
                traceFolder = traceFolder,
                value0 = value0,
                versionCode = versionCode,
                versionCodeMajor = versionCodeMajor,
                versionName = versionName,
                warnManifestValidation = warnManifestValidation
            )
        }
    }
}
