// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.aapt2.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.aapt2.*
import java.io.File

public class OptimizeCliCommand(
    private val useCase: OptimizeUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "optimize") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(OptimizeUseCase(repository), context)

    override fun help(context: Context): String = "aapt2 optimize [options] files..."

    public val C: Boolean by option("--c", "-c", help = "arg                                            Comma separated list of configurations to include. The default").flag()
    public val D: Boolean by option("--d", "-d", help = "arg                                            Path to the output directory (for splits).").flag()
    public val O: Boolean by option("--o", "-o", help = "arg                                            Path to the output APK.").flag()
    public val P: Boolean by option("--p", "-p", help = "Print the multi APK artifacts and exit.").flag()
    public val V: Boolean by option("--v", "-v", help = "Enables verbose logging").flag()
    public val X: Boolean by option("--x", "-x", help = "arg                                            Path to XML configuration file.").flag()
    public val collapseResourceNames: Boolean by option("--collapse-resource-names", help = "Collapses resource names to a single value in the key string pool. Resources can").flag()
    public val deduplicateEntryValues: Boolean by option("--deduplicate-entry-values", help = "Whether to deduplicate pairs of resource entry and value for simple resources.").flag()
    public val enableCompactEntries: Boolean by option("--enable-compact-entries", help = "This decreases APK size by using compact resource entries for simple data types.").flag()
    public val enableSparseEncoding: Boolean by option("--enable-sparse-encoding", help = "Enables encoding sparse entries using a binary search tree.").flag()
    public val forceSparseEncoding: Boolean by option("--force-sparse-encoding", help = "Enables encoding sparse entries using a binary search tree.").flag()
    public val help: Boolean by option("--help", help = "Displays this help menu").flag()
    public val keepArtifacts: Boolean by option("--keep-artifacts", help = "arg                              Comma separated list of artifacts to keep. If none are specified,").flag()
    public val resourcePathShorteningMap: Boolean by option("--resource-path-shortening-map", help = "arg                [Deprecated]Path to output the map of old resource paths to shortened paths.").flag()
    public val resourcesConfigPath: Boolean by option("--resources-config-path", help = "arg                       Path to the resources.cfg file containing the list of resources and").flag()
    public val saveObfuscationMap: Boolean by option("--save-obfuscation-map", help = "arg                        Path to output the map of original paths/names to obfuscated paths/names.").flag()
    public val shortenResourcePaths: Boolean by option("--shorten-resource-paths", help = "Shortens the paths of resources inside the APK. Resources can be exempted using the").flag()
    public val split: Boolean by option("--split", help = "arg                                       Split resources matching a set of configs out to a Split APK.").flag()
    public val targetDensities: Boolean by option("--target-densities", help = "arg                            Comma separated list of the screen densities that the APK will be optimized for.").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                C = C,
                D = D,
                O = O,
                P = P,
                V = V,
                X = X,
                collapseResourceNames = collapseResourceNames,
                deduplicateEntryValues = deduplicateEntryValues,
                enableCompactEntries = enableCompactEntries,
                enableSparseEncoding = enableSparseEncoding,
                forceSparseEncoding = forceSparseEncoding,
                help = help,
                keepArtifacts = keepArtifacts,
                resourcePathShorteningMap = resourcePathShorteningMap,
                resourcesConfigPath = resourcesConfigPath,
                saveObfuscationMap = saveObfuscationMap,
                shortenResourcePaths = shortenResourcePaths,
                split = split,
                targetDensities = targetDensities
            )
        }
    }
}
