// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.fec

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ExecuteUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        H: Boolean = false,
        S: Boolean = false,
        V: Boolean = false,
        inplace: Boolean = false,
        padding: String? = null,
        roots: String? = null,
        threads: String? = null,
        positionalArgs: List<String> = emptyList()
    ): String {
        val command = ExecuteCommand(
            H = H,
            S = S,
            V = V,
            inplace = inplace,
            padding = padding,
            roots = roots,
            threads = threads,
            positionalArgs = positionalArgs
        )
        return repository.execute(command, context)
    }
}
