// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.fsckerofs

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ExecuteUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        A: Boolean = false,
        D: String? = null,
        P: Boolean = false,
        device: String? = null,
        extract: String? = null,
        force: Boolean = false,
        help: Boolean = false,
        offset: String? = null,
        overwrite: Boolean = false,
        version: Boolean = false,
        positionalArgs: List<String> = emptyList()
    ): String {
        val command = ExecuteCommand(
            A = A,
            D = D,
            P = P,
            device = device,
            extract = extract,
            force = force,
            help = help,
            offset = offset,
            overwrite = overwrite,
            version = version,
            positionalArgs = positionalArgs
        )
        return repository.execute(command, context)
    }
}
