// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.avbtool.*
import java.io.File

public class AddHashtreeFooterCliCommand(
    private val useCase: AddHashtreeFooterUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "add_hashtree_footer") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(AddHashtreeFooterUseCase(repository), context)

    override fun help(context: Context): String = "usage: avbtool add_hashtree_footer [-h] [--image IMAGE]"

    public val algorithm: String? by option("--algorithm", help = "Algorithm to use (default: NONE)")
    public val appendToReleaseString: String? by option("--append_to_release_string", help = "Text to append to release string")
    public val blockSize: String? by option("--block_size", help = "Block size (default: 4096)")
    public val calcMaxImageSize: Boolean by option("--calc_max_image_size", help = "Don't store the hashtree or footer - instead calculate").flag()
    public val chainPartition: Boolean by option("--chain_partition", help = "PART_NAME:ROLLBACK_SLOT:KEY_PATH").flag()
    public val chainPartitionDoNotUseAb: Boolean by option("--chain_partition_do_not_use_ab", help = "PART_NAME:ROLLBACK_SLOT:KEY_PATH").flag()
    public val checkAtMostOnce: Boolean by option("--check_at_most_once", help = "Set to verify data block only once").flag()
    public val doNotAppendVbmetaImage: Boolean by option("--do_not_append_vbmeta_image", help = "Do not append vbmeta struct or footer to the image").flag()
    public val doNotGenerateFec: Boolean by option("--do_not_generate_fec", help = "Do not generate forward-error-correction codes").flag()
    public val doNotUseAb: Boolean by option("--do_not_use_ab", help = "The partition does not use A/B even when an A/B suffix").flag()
    public val fecNumRoots: String? by option("--fec_num_roots", help = "Number of roots for FEC (default: 2)")
    public val flags: String? by option("--flags", help = "VBMeta flags")
    public val hashAlgorithm: String? by option("--hash_algorithm", help = "Hash algorithm to use (default: sha1)")
    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()
    public val image: String? by option("--image", help = "Image to add hashtree to")
    public val includeDescriptorsFromImage: String? by option("--include_descriptors_from_image", help = "Include descriptors from image")
    public val kernelCmdline: String? by option("--kernel_cmdline", help = "Add kernel cmdline")
    public val key: String? by option("--key", help = "Path to RSA private key file")
    public val noHashtree: Boolean by option("--no_hashtree", help = "Do not append hashtree").flag()
    public val outputVbmetaImage: String? by option("--output_vbmeta_image", help = "Also write vbmeta struct to file")
    public val partitionName: String? by option("--partition_name", help = "Partition name")
    public val partitionSize: String? by option("--partition_size", help = "Partition size")
    public val printRequiredLibavbVersion: Boolean by option("--print_required_libavb_version", help = "Don't store the footer - instead calculate the").flag()
    public val prop: Boolean by option("--prop", help = "KEY:VALUE      Add property").flag()
    public val propFromFile: Boolean by option("--prop_from_file", help = "KEY:PATH").flag()
    public val publicKeyMetadata: String? by option("--public_key_metadata", help = "Path to public key metadata file")
    public val rollbackIndex: String? by option("--rollback_index", help = "Rollback Index")
    public val rollbackIndexLocation: String? by option("--rollback_index_location", help = "Location of main vbmeta Rollback Index")
    public val salt: String? by option("--salt", help = "Salt in hex (default: /dev/urandom)")
    public val setHashtreeDisabledFlag: Boolean by option("--set_hashtree_disabled_flag", help = "Set the HASHTREE_DISABLED flag").flag()
    public val setVerificationDisabledFlag: Boolean by option("--set_verification_disabled_flag", help = "Set the VERIFICATION_DISABLED flag").flag()
    public val setupAsRootfsFromKernel: Boolean by option("--setup_as_rootfs_from_kernel", help = "Adds kernel cmdline for setting up rootfs").flag()
    public val setupRootfsFromKernel: Boolean by option("--setup_rootfs_from_kernel", help = "IMAGE, --generate_dm_verity_cmdline_from_hashtree IMAGE").flag()
    public val signingHelper: String? by option("--signing_helper", help = "Path to helper used for signing")
    public val signingHelperWithFiles: String? by option("--signing_helper_with_files", help = "Path to helper used for signing using files")
    public val usePersistentDigest: Boolean by option("--use_persistent_digest", help = "Use a persistent digest on device instead of storing").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                algorithm = algorithm,
                appendToReleaseString = appendToReleaseString,
                blockSize = blockSize,
                calcMaxImageSize = calcMaxImageSize,
                chainPartition = chainPartition,
                chainPartitionDoNotUseAb = chainPartitionDoNotUseAb,
                checkAtMostOnce = checkAtMostOnce,
                doNotAppendVbmetaImage = doNotAppendVbmetaImage,
                doNotGenerateFec = doNotGenerateFec,
                doNotUseAb = doNotUseAb,
                fecNumRoots = fecNumRoots,
                flags = flags,
                hashAlgorithm = hashAlgorithm,
                help = help,
                image = image,
                includeDescriptorsFromImage = includeDescriptorsFromImage,
                kernelCmdline = kernelCmdline,
                key = key,
                noHashtree = noHashtree,
                outputVbmetaImage = outputVbmetaImage,
                partitionName = partitionName,
                partitionSize = partitionSize,
                printRequiredLibavbVersion = printRequiredLibavbVersion,
                prop = prop,
                propFromFile = propFromFile,
                publicKeyMetadata = publicKeyMetadata,
                rollbackIndex = rollbackIndex,
                rollbackIndexLocation = rollbackIndexLocation,
                salt = salt,
                setHashtreeDisabledFlag = setHashtreeDisabledFlag,
                setVerificationDisabledFlag = setVerificationDisabledFlag,
                setupAsRootfsFromKernel = setupAsRootfsFromKernel,
                setupRootfsFromKernel = setupRootfsFromKernel,
                signingHelper = signingHelper,
                signingHelperWithFiles = signingHelperWithFiles,
                usePersistentDigest = usePersistentDigest
            )
        }
    }
}
