// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.avbtool.*
import java.io.File

public class AppendVbmetaImageCliCommand(
    private val useCase: AppendVbmetaImageUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "append_vbmeta_image") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(AppendVbmetaImageUseCase(repository), context)

    override fun help(context: Context): String = "usage: avbtool append_vbmeta_image [-h] [--image IMAGE] --partition_size"

    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()
    public val image: String? by option("--image", help = "Image to append vbmeta blob to")
    public val partitionSize: String? by option("--partition_size", help = "Partition size")
    public val vbmetaImage: String? by option("--vbmeta_image", help = "Image with vbmeta blob to append")

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                image = image,
                partitionSize = partitionSize,
                vbmetaImage = vbmetaImage
            )
        }
    }
}
