// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.avbtool.*
import java.io.File

public class EraseFooterCliCommand(
    private val useCase: EraseFooterUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "erase_footer") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(EraseFooterUseCase(repository), context)

    override fun help(context: Context): String = "usage: avbtool erase_footer [-h] --image IMAGE [--keep_hashtree]"

    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()
    public val image: String? by option("--image", help = "Image with a footer")
    public val keepHashtree: Boolean by option("--keep_hashtree", help = "Keep the hashtree and FEC in the image").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                image = image,
                keepHashtree = keepHashtree
            )
        }
    }
}
