// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.avbtool.*
import java.io.File

public class ExtractVbmetaImageCliCommand(
    private val useCase: ExtractVbmetaImageUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "extract_vbmeta_image") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ExtractVbmetaImageUseCase(repository), context)

    override fun help(context: Context): String = "usage: avbtool extract_vbmeta_image [-h] --image IMAGE [--output OUTPUT]"

    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()
    public val image: String? by option("--image", help = "Image with footer")
    public val output: String? by option("--output", help = "Output file name")
    public val paddingSize: String? by option("--padding_size", help = "If non-zero, pads output with NUL bytes so its size is")

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                image = image,
                output = output,
                paddingSize = paddingSize
            )
        }
    }
}
