// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.avbtool.*
import java.io.File

public class GenerateTestImageCliCommand(
    private val useCase: GenerateTestImageUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "generate_test_image") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(GenerateTestImageUseCase(repository), context)

    override fun help(context: Context): String = "usage: avbtool generate_test_image [-h] --image_size IMAGE_SIZE"

    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()
    public val imageSize: String? by option("--image_size", help = "Size of image to generate.")
    public val output: String? by option("--output", help = "Output file name.")
    public val startByte: String? by option("--start_byte", help = "Integer for the start byte of the pattern.")

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                imageSize = imageSize,
                output = output,
                startByte = startByte
            )
        }
    }
}
