// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.avbtool.*
import java.io.File

public class MakeAtxPermanentAttributesCliCommand(
    private val useCase: MakeAtxPermanentAttributesUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "make_atx_permanent_attributes") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(MakeAtxPermanentAttributesUseCase(repository), context)

    override fun help(context: Context): String = "usage: avbtool make_cert_permanent_attributes [-h] [--output OUTPUT]"

    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()
    public val output: String? by option("--output", help = "Write attributes to file")
    public val productId: String? by option("--product_id", help = "Path to Product ID file")
    public val rootAuthorityKey: Boolean by option("--root_authority_key", help = "ROOT_AUTHORITY_KEY --product_id").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                output = output,
                productId = productId,
                rootAuthorityKey = rootAuthorityKey
            )
        }
    }
}
