// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.avbtool.*
import java.io.File

public class PrintPartitionDigestsCliCommand(
    private val useCase: PrintPartitionDigestsUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "print_partition_digests") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(PrintPartitionDigestsUseCase(repository), context)

    override fun help(context: Context): String = "usage: avbtool print_partition_digests [-h] --image IMAGE [--output OUTPUT]"

    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()
    public val image: String? by option("--image", help = "Image to print partition digests from")
    public val json: Boolean by option("--json", help = "Print output as JSON").flag()
    public val output: String? by option("--output", help = "Write info to file")

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                image = image,
                json = json,
                output = output
            )
        }
    }
}
