// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.avbtool.*
import java.io.File

public class ResizeImageCliCommand(
    private val useCase: ResizeImageUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "resize_image") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ResizeImageUseCase(repository), context)

    override fun help(context: Context): String = "usage: avbtool resize_image [-h] --image IMAGE"

    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()
    public val image: String? by option("--image", help = "Image with a footer")
    public val partitionSize: String? by option("--partition_size", help = "New partition size")

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                help = help,
                image = image,
                partitionSize = partitionSize
            )
        }
    }
}
