// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.avbtool.*
import java.io.File

public class ResignImageCliCommand(
    private val useCase: ResignImageUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "resign_image") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ResignImageUseCase(repository), context)

    override fun help(context: Context): String = "usage: avbtool resign_image [-h] --image IMAGE --key KEY --algorithm ALGORITHM"

    public val algorithm: String? by option("--algorithm", help = "Algorithm to use")
    public val autoResize: Boolean by option("--auto_resize", help = "Automatically resize the image if the new key is").flag()
    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()
    public val image: String? by option("--image", help = "Image to resign")
    public val key: String? by option("--key", help = "Path to RSA private key file")
    public val signingHelper: String? by option("--signing_helper", help = "Program that signs a hash and returns a signature.")
    public val signingHelperWithFiles: File? by option("--signing_helper_with_files", help = "Same as signing_helper but uses files for").convert { File(it) }

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                algorithm = algorithm,
                autoResize = autoResize,
                help = help,
                image = image,
                key = key,
                signingHelper = signingHelper,
                signingHelperWithFiles = signingHelperWithFiles
            )
        }
    }
}
