// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.avbtool.*
import java.io.File

public class VerifyImageCliCommand(
    private val useCase: VerifyImageUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "verify_image") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(VerifyImageUseCase(repository), context)

    override fun help(context: Context): String = "usage: avbtool verify_image [-h] --image IMAGE [--key KEY]"

    public val acceptZeroedHashtree: Boolean by option("--accept_zeroed_hashtree", help = "Accept images where the hashtree or FEC data is zeroed").flag()
    public val expectedChainPartition: Boolean by option("--expected_chain_partition", help = "PART_NAME:ROLLBACK_SLOT:KEY_PATH").flag()
    public val followChainPartitions: Boolean by option("--follow_chain_partitions", help = "Follows chain partitions even when not specified with").flag()
    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()
    public val image: String? by option("--image", help = "Image to verify")
    public val key: String? by option("--key", help = "Check embedded public key matches KEY")

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                acceptZeroedHashtree = acceptZeroedHashtree,
                expectedChainPartition = expectedChainPartition,
                followChainPartitions = followChainPartitions,
                help = help,
                image = image,
                key = key
            )
        }
    }
}
