// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.lpdump

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class ExecuteCommand(
    public val all: Boolean = false,
    public val dumpMetadataSize: Boolean = false,
    public val json: Boolean = false,
    public val slot: String? = null,
    public val positionalArgs: List<String> = emptyList()
) : ToolCommand<io.ltirom.tooling.core.DynamicPartitionMetadata> {

    override val toolId: ToolId get() = ToolId.LPDUMP
    override val risk: ToolRisk get() = ToolRisk.READ_ONLY
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<io.ltirom.tooling.core.DynamicPartitionMetadata> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("lp-metadata") as io.ltirom.tooling.core.ToolOutputParser<io.ltirom.tooling.core.DynamicPartitionMetadata>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): io.ltirom.tooling.core.DynamicPartitionMetadata {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        if (all) args.add("--all")
        if (dumpMetadataSize) args.add("--dump-metadata-size")
        if (json) args.add("--json")
        slot?.let { val value = it
            args.add("--slot")
            args.add(value.toString())
        }
        for (item in positionalArgs) {
            args.add(item.toString())
        }
        return args
    }
}
