// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.lpdump

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ExecuteUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        all: Boolean = false,
        dumpMetadataSize: Boolean = false,
        json: Boolean = false,
        slot: String? = null,
        positionalArgs: List<String> = emptyList()
    ): io.ltirom.tooling.core.DynamicPartitionMetadata {
        val command = ExecuteCommand(
            all = all,
            dumpMetadataSize = dumpMetadataSize,
            json = json,
            slot = slot,
            positionalArgs = positionalArgs
        )
        return repository.execute(command, context)
    }
}
