// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.adb

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class InstallUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        downgrade: Boolean = false,
        exitOnWriteError: Boolean = false,
        grantPermissions: Boolean = false,
        listenAll: Boolean = false,
        oneDevice: String? = null,
        replace: Boolean = false,
        serial: String? = null,
        serverHost: String? = null,
        serverPort: Int? = null,
        serverSocket: String? = null,
        testPackages: Boolean = false,
        transportId: String? = null,
        useTcp: Boolean = false,
        useUsb: Boolean = false,
        packagePath: File
    ): Unit {
        val command = InstallCommand(
            downgrade = downgrade,
            exitOnWriteError = exitOnWriteError,
            grantPermissions = grantPermissions,
            listenAll = listenAll,
            oneDevice = oneDevice,
            replace = replace,
            serial = serial,
            serverHost = serverHost,
            serverPort = serverPort,
            serverSocket = serverSocket,
            testPackages = testPackages,
            transportId = transportId,
            useTcp = useTcp,
            useUsb = useUsb,
            packagePath = packagePath
        )
        return repository.execute(command, context)
    }
}
