// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.adb

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class JdwpUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        exitOnWriteError: Boolean = false,
        listenAll: Boolean = false,
        oneDevice: String? = null,
        serial: String? = null,
        serverHost: String? = null,
        serverPort: Int? = null,
        serverSocket: String? = null,
        transportId: String? = null,
        useTcp: Boolean = false,
        useUsb: Boolean = false
    ): String {
        val command = JdwpCommand(
            exitOnWriteError = exitOnWriteError,
            listenAll = listenAll,
            oneDevice = oneDevice,
            serial = serial,
            serverHost = serverHost,
            serverPort = serverPort,
            serverSocket = serverSocket,
            transportId = transportId,
            useTcp = useTcp,
            useUsb = useUsb
        )
        return repository.execute(command, context)
    }
}
