// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.adb

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class LogcatUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        clearLogs: Boolean = false,
        dumpLogs: Boolean = false,
        exitOnWriteError: Boolean = false,
        listenAll: Boolean = false,
        logFormat: String? = null,
        oneDevice: String? = null,
        outputFile: File? = null,
        serial: String? = null,
        serverHost: String? = null,
        serverPort: Int? = null,
        serverSocket: String? = null,
        transportId: String? = null,
        useTcp: Boolean = false,
        useUsb: Boolean = false,
        filters: List<String> = emptyList()
    ): String {
        val command = LogcatCommand(
            clearLogs = clearLogs,
            dumpLogs = dumpLogs,
            exitOnWriteError = exitOnWriteError,
            listenAll = listenAll,
            logFormat = logFormat,
            oneDevice = oneDevice,
            outputFile = outputFile,
            serial = serial,
            serverHost = serverHost,
            serverPort = serverPort,
            serverSocket = serverSocket,
            transportId = transportId,
            useTcp = useTcp,
            useUsb = useUsb,
            filters = filters
        )
        return repository.execute(command, context)
    }
}
