// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.adb

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class PushUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        compression: String? = null,
        disableCompression: Boolean = false,
        exitOnWriteError: Boolean = false,
        listenAll: Boolean = false,
        oneDevice: String? = null,
        serial: String? = null,
        serverHost: String? = null,
        serverPort: Int? = null,
        serverSocket: String? = null,
        sync: Boolean = false,
        transportId: String? = null,
        useTcp: Boolean = false,
        useUsb: Boolean = false,
        local: File,
        remote: String
    ): io.ltirom.tooling.core.AdbTransferProgress {
        val command = PushCommand(
            compression = compression,
            disableCompression = disableCompression,
            exitOnWriteError = exitOnWriteError,
            listenAll = listenAll,
            oneDevice = oneDevice,
            serial = serial,
            serverHost = serverHost,
            serverPort = serverPort,
            serverSocket = serverSocket,
            sync = sync,
            transportId = transportId,
            useTcp = useTcp,
            useUsb = useUsb,
            local = local,
            remote = remote
        )
        return repository.execute(command, context)
    }
}
