// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.adb

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class PushCommand(
    public val compression: String? = null,
    public val disableCompression: Boolean = false,
    public val exitOnWriteError: Boolean = false,
    public val listenAll: Boolean = false,
    public val oneDevice: String? = null,
    public val serial: String? = null,
    public val serverHost: String? = null,
    public val serverPort: Int? = null,
    public val serverSocket: String? = null,
    public val sync: Boolean = false,
    public val transportId: String? = null,
    public val useTcp: Boolean = false,
    public val useUsb: Boolean = false,
    public val local: File,
    public val remote: String
) : ToolCommand<io.ltirom.tooling.core.AdbTransferProgress> {

    override val toolId: ToolId get() = ToolId.ADB
    override val risk: ToolRisk get() = ToolRisk.DEVICE_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<io.ltirom.tooling.core.AdbTransferProgress> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("adb-transfer-progress") as io.ltirom.tooling.core.ToolOutputParser<io.ltirom.tooling.core.AdbTransferProgress>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): io.ltirom.tooling.core.AdbTransferProgress {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("push")
        compression?.let { val value = it
            args.add("-z")
            args.add(value.toString())
        }
        if (disableCompression) args.add("-Z")
        if (exitOnWriteError) args.add("--exit-on-write-error")
        if (listenAll) args.add("-a")
        oneDevice?.let { val value = it
            args.add("--one-device")
            args.add(value.toString())
        }
        serial?.let { val value = it
            args.add("-s")
            args.add(value.toString())
        }
        serverHost?.let { val value = it
            args.add("-H")
            args.add(value.toString())
        }
        serverPort?.let { val value = it
            args.add("-P")
            args.add(value.toString())
        }
        serverSocket?.let { val value = it
            args.add("-L")
            args.add(value.toString())
        }
        if (sync) args.add("--sync")
        transportId?.let { val value = it
            args.add("-t")
            args.add(value.toString())
        }
        if (useTcp) args.add("-e")
        if (useUsb) args.add("-d")
        args.add(local.toString())
        args.add(remote.toString())
        return args
    }
}
