// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.adb

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ShellUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        disableExitSeparation: Boolean = false,
        disablePty: Boolean = false,
        escapeChar: String? = null,
        exitOnWriteError: Boolean = false,
        forcePty: Boolean = false,
        listenAll: Boolean = false,
        noStdin: Boolean = false,
        oneDevice: String? = null,
        serial: String? = null,
        serverHost: String? = null,
        serverPort: Int? = null,
        serverSocket: String? = null,
        transportId: String? = null,
        useTcp: Boolean = false,
        useUsb: Boolean = false,
        command: List<String> = emptyList()
    ): String {
        val command = ShellCommand(
            disableExitSeparation = disableExitSeparation,
            disablePty = disablePty,
            escapeChar = escapeChar,
            exitOnWriteError = exitOnWriteError,
            forcePty = forcePty,
            listenAll = listenAll,
            noStdin = noStdin,
            oneDevice = oneDevice,
            serial = serial,
            serverHost = serverHost,
            serverPort = serverPort,
            serverSocket = serverSocket,
            transportId = transportId,
            useTcp = useTcp,
            useUsb = useUsb,
            command = command
        )
        return repository.execute(command, context)
    }
}
