/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package org.ide.lti.feature.settings.components

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.AltRoute
import androidx.compose.material.icons.automirrored.filled.HelpOutline
import androidx.compose.material.icons.automirrored.filled.MenuBook
import androidx.compose.material.icons.automirrored.filled.OpenInNew
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Description
import androidx.compose.material.icons.filled.Speed
import androidx.compose.material.icons.filled.Storage
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import org.ide.lti.core.designsystem.component.display.GlassCard
import org.ide.lti.core.designsystem.component.display.GlassHorizontalDivider
import org.ide.lti.core.designsystem.component.display.LtiRomStudioMark
import org.ide.lti.core.designsystem.theme.AlphaTokens
import org.ide.lti.core.designsystem.theme.BrandColors
import org.ide.lti.core.designsystem.theme.ComponentSize
import org.ide.lti.core.designsystem.theme.FontSize
import org.ide.lti.core.designsystem.theme.GlassDimens
import org.ide.lti.core.designsystem.theme.GlassShapes
import org.ide.lti.core.designsystem.theme.GlassTheme
import org.ide.lti.core.designsystem.theme.IconSize
import org.ide.lti.core.designsystem.theme.Spacing
import org.ide.lti.core.designsystem.theme.codeFontFamily

/**
 * High-fidelity About Settings Pane matching the Stitch & Fleet design standards (Image 1).
 *
 * Implements:
 * - Breadcrumbs: Settings / About
 * - Hero Header Card with 3D logo box, title, and development build badge
 * - Description paragraph
 * - 4 Quick Link Action Cards (Documentation, Source code, Licenses, Get support) with external link icon
 * - Lower 2-column grid: Technical Information table & Diagnostics report card
 * - Bottom status bar with storage profile & connection status
 */
// LongMethod suppressed on @Composable screen pane for about settings.
@Suppress("LongMethod")
@Composable
fun AboutSettingsPane(modifier: Modifier = Modifier, appVersion: String = "0.9.0-dev (build 2024.10.12.42)") {
    var reportGenerated by remember { mutableStateOf(false) }

    Column(
        modifier = modifier.fillMaxWidth().testTag("AboutSettingsPane"),
        verticalArrangement = Arrangement.spacedBy(Spacing.Large),
    ) {
        // Breadcrumb Navigation
        Row(
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(Spacing.Small),
        ) {
            Text(
                text = "Settings",
                fontSize = FontSize.BodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
            Text(
                text = "/",
                fontSize = FontSize.BodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
            Text(
                text = "About",
                fontSize = FontSize.BodySmall,
                fontWeight = FontWeight.SemiBold,
                color = MaterialTheme.colorScheme.onSurface,
            )
        }

        // Hero Header Card
        GlassCard(
            modifier = Modifier.fillMaxWidth().testTag("AboutHeroHeaderCard"),
            surfaceColor = MaterialTheme.colorScheme.surfaceContainerHigh,
            contentPadding = Spacing.CardPadding,
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically,
            ) {
                // Left 3D Brand Mark & Headings
                Row(
                    horizontalArrangement = Arrangement.spacedBy(Spacing.Large),
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    Box(
                        modifier = Modifier
                            .size(ComponentSize.AboutLogoBoxSize)
                            .clip(GlassShapes.MediumSmall)
                            .background(MaterialTheme.colorScheme.primary.copy(alpha = AlphaTokens.Faded))
                            .border(
                                width = GlassDimens.HairlineBorder,
                                color = MaterialTheme.colorScheme.outline,
                                shape = GlassShapes.MediumSmall,
                            ),
                        contentAlignment = Alignment.Center,
                    ) {
                        LtiRomStudioMark(
                            modifier = Modifier.size(IconSize.ExtraLarge),
                            tint = MaterialTheme.colorScheme.primary,
                        )
                    }

                    Column(verticalArrangement = Arrangement.spacedBy(Spacing.ExtraExtraSmall)) {
                        Text(
                            text = "About LtiRom Studio",
                            fontSize = FontSize.HeadlineMedium,
                            fontWeight = FontWeight.Bold,
                            color = MaterialTheme.colorScheme.onSurface,
                        )
                        Text(
                            text = "Build. Modify. Publish with confidence.",
                            fontSize = FontSize.TitleSmall,
                            fontWeight = FontWeight.Medium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                        Text(
                            text = "LtiRom Studio · A modern workspace for ROM building",
                            fontSize = FontSize.BodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                    }
                }

                // Right Version Badge Box
                Box(
                    modifier = Modifier
                        .clip(GlassShapes.MediumSmall)
                        .background(MaterialTheme.colorScheme.surfaceContainerHigh)
                        .border(
                            width = GlassDimens.HairlineBorder,
                            color = MaterialTheme.colorScheme.outline,
                            shape = GlassShapes.MediumSmall,
                        )
                        .padding(Spacing.Medium),
                ) {
                    Column(verticalArrangement = Arrangement.spacedBy(Spacing.ExtraSmall)) {
                        Text(
                            text = "Version",
                            fontSize = FontSize.LabelSmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                        Text(
                            text = "Development build",
                            fontSize = FontSize.BodyMedium,
                            fontWeight = FontWeight.Bold,
                            color = MaterialTheme.colorScheme.onSurface,
                        )
                        Text(
                            text = "Version $appVersion",
                            fontSize = FontSize.LabelSmall,
                            fontFamily = codeFontFamily(),
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(Spacing.Small),
                        ) {
                            Box(
                                modifier = Modifier
                                    .size(Spacing.Small)
                                    .clip(GlassShapes.Circle)
                                    .background(GlassTheme.diagnosticColors.success),
                            )
                            Text(
                                text = "You are running the latest development build",
                                fontSize = FontSize.LabelSmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant,
                            )
                        }
                    }
                }
            }
        }

        // Description Paragraph
        Text(
            text = "LtiRom Studio helps you acquire, prepare, customize and build Android ROMs in a focused, " +
                "modern workspace. This development build provides early access to new features. " +
                "Features and behavior may change before a stable release.",
            fontSize = FontSize.BodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            modifier = Modifier.padding(horizontal = Spacing.ExtraSmall),
        )

        // 4 Action Link Cards Row
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(Spacing.Medium),
        ) {
            AboutActionCard(
                title = "Documentation",
                subtitle = "Guides and help topics",
                icon = Icons.AutoMirrored.Filled.MenuBook,
                onClick = {},
                modifier = Modifier.weight(1f),
            )
            AboutActionCard(
                title = "Source code",
                subtitle = "View on GitHub",
                icon = Icons.AutoMirrored.Filled.AltRoute,
                onClick = {},
                modifier = Modifier.weight(1f),
            )
            AboutActionCard(
                title = "Licenses",
                subtitle = "Open source components",
                icon = Icons.Default.Description,
                onClick = {},
                modifier = Modifier.weight(1f),
            )
            AboutActionCard(
                title = "Get support",
                subtitle = "Help and community",
                icon = Icons.AutoMirrored.Filled.HelpOutline,
                onClick = {},
                modifier = Modifier.weight(1f),
            )
        }

        // Lower Grid: Technical Information (weight 1.1f) & Diagnostics (weight 0.9f)
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(Spacing.Large),
        ) {
            // Technical Information Card
            GlassCard(
                modifier = Modifier.weight(1.15f),
                surfaceColor = MaterialTheme.colorScheme.surfaceContainerHigh,
                contentPadding = Spacing.CardPadding,
            ) {
                Column(verticalArrangement = Arrangement.spacedBy(Spacing.Medium)) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(Spacing.Small),
                    ) {
                        Icon(
                            imageVector = Icons.Default.Storage,
                            contentDescription = null,
                            tint = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.size(IconSize.Medium),
                        )
                        Text(
                            text = "Technical information",
                            fontSize = FontSize.TitleMedium,
                            fontWeight = FontWeight.SemiBold,
                            color = MaterialTheme.colorScheme.onSurface,
                        )
                    }

                    Column(verticalArrangement = Arrangement.spacedBy(Spacing.SmallMedium)) {
                        TechInfoRow("Application version", appVersion)
                        GlassHorizontalDivider()
                        TechInfoRow("Kotlin SDK version", "2.1.0")
                        GlassHorizontalDivider()
                        TechInfoRow(
                            "Runtime",
                            "JDK 21.0.2 (OpenJDK 64-Bit)",
                        )
                        GlassHorizontalDivider()
                        TechInfoRow(
                            "Operating system",
                            "Windows 11 23H2 (22631.4317)",
                        )
                        GlassHorizontalDivider()
                        TechInfoRow(
                            "User data directory",
                            "C:\\Users\\devuser\\AppData\\Roaming\\LtiRom Studio",
                        )
                        GlassHorizontalDivider()
                        TechInfoRow(
                            "Configuration directory",
                            "C:\\Users\\devuser\\AppData\\Roaming\\LtiRom Studio\\config",
                        )
                        GlassHorizontalDivider()
                        TechInfoRow(
                            "Logs directory",
                            "C:\\Users\\devuser\\AppData\\Roaming\\LtiRom Studio\\logs",
                        )
                    }
                }
            }

            // Diagnostics Card
            GlassCard(
                modifier = Modifier.weight(0.85f),
                surfaceColor = MaterialTheme.colorScheme.surfaceContainerHigh,
                contentPadding = Spacing.CardPadding,
            ) {
                Column(verticalArrangement = Arrangement.spacedBy(Spacing.Medium)) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(Spacing.Small),
                    ) {
                        Icon(
                            imageVector = Icons.Default.Speed,
                            contentDescription = null,
                            tint = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.size(IconSize.Medium),
                        )
                        Text(
                            text = "Diagnostics",
                            fontSize = FontSize.TitleMedium,
                            fontWeight = FontWeight.SemiBold,
                            color = MaterialTheme.colorScheme.onSurface,
                        )
                    }

                    Text(
                        text = "Collect diagnostic information to help troubleshoot issues. " +
                            "The report contains configuration details, environment information and recent logs. " +
                            "No personal files are included.",
                        fontSize = FontSize.BodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )

                    Spacer(modifier = Modifier.height(Spacing.Small))

                    // Generate Diagnostic Report Button
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clip(GlassShapes.Small)
                            .background(MaterialTheme.colorScheme.primary)
                            .border(
                                width = GlassDimens.HairlineBorder,
                                color = MaterialTheme.colorScheme.primary,
                                shape = GlassShapes.Small,
                            )
                            .clickable(
                                interactionSource = remember { MutableInteractionSource() },
                                indication = null,
                                onClick = { reportGenerated = true },
                            )
                            .padding(vertical = Spacing.SmallMedium),
                        contentAlignment = Alignment.Center,
                    ) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(Spacing.Small),
                        ) {
                            Icon(
                                imageVector = if (reportGenerated) {
                                    Icons.Default.CheckCircle
                                } else {
                                    Icons.Default.Description
                                },
                                contentDescription = null,
                                tint = BrandColors.OnLogoBadge,
                                modifier = Modifier.size(IconSize.Medium),
                            )
                            Text(
                                text = if (reportGenerated) {
                                    "Diagnostic report generated"
                                } else {
                                    "Generate diagnostic report"
                                },
                                fontSize = FontSize.BodySmall,
                                fontWeight = FontWeight.SemiBold,
                                color = BrandColors.OnLogoBadge,
                            )
                        }
                    }

                    Text(
                        text = "The report will be saved to your logs directory.",
                        fontSize = FontSize.LabelSmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
            }
        }

        // Bottom Status Bar
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(vertical = Spacing.Small)
                .testTag("AboutStatusBar"),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(Spacing.Small),
            ) {
                Icon(
                    imageVector = Icons.Default.Storage,
                    contentDescription = null,
                    tint = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.size(IconSize.Small),
                )
                Text(
                    text = "Settings are stored in your user profile",
                    fontSize = FontSize.LabelSmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }

            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(Spacing.Medium),
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(Spacing.ExtraSmall),
                ) {
                    Box(
                        modifier = Modifier
                            .size(Spacing.Small)
                            .clip(GlassShapes.Circle)
                            .background(GlassTheme.diagnosticColors.success),
                    )
                    Text(
                        text = "Connected",
                        fontSize = FontSize.LabelSmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }

                Text(
                    text = "Design concept · Sample data",
                    fontSize = FontSize.LabelSmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        }
    }
}

@Composable
private fun AboutActionCard(
    title: String,
    subtitle: String,
    icon: ImageVector,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
) {
    Box(
        modifier = modifier
            .height(ComponentSize.AboutLinkCardHeight)
            .clip(GlassShapes.MediumSmall)
            .background(MaterialTheme.colorScheme.surfaceContainerHigh)
            .border(
                width = GlassDimens.HairlineBorder,
                color = MaterialTheme.colorScheme.outline,
                shape = GlassShapes.MediumSmall,
            )
            .clickable(
                interactionSource = remember { MutableInteractionSource() },
                indication = null,
                onClick = onClick,
            )
            .padding(Spacing.Medium),
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.Top,
        ) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(Spacing.SmallMedium),
                modifier = Modifier.weight(1f),
            ) {
                Icon(
                    imageVector = icon,
                    contentDescription = null,
                    tint = MaterialTheme.colorScheme.primary,
                    modifier = Modifier.size(IconSize.Large),
                )
                Column(verticalArrangement = Arrangement.spacedBy(Spacing.ExtraExtraSmall)) {
                    Text(
                        text = title,
                        fontSize = FontSize.BodyMedium,
                        fontWeight = FontWeight.SemiBold,
                        color = MaterialTheme.colorScheme.onSurface,
                    )
                    Text(
                        text = subtitle,
                        fontSize = FontSize.LabelSmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
            }

            Icon(
                imageVector = Icons.AutoMirrored.Filled.OpenInNew,
                contentDescription = "Open",
                tint = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.size(IconSize.Small),
            )
        }
    }
}

@Composable
private fun TechInfoRow(label: String, value: String) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(
            text = label,
            fontSize = FontSize.BodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        Text(
            text = value,
            fontSize = FontSize.BodySmall,
            fontFamily = codeFontFamily(),
            color = MaterialTheme.colorScheme.onSurface,
        )
    }
}
