// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class AddHashtreeFooterUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        algorithm: String? = null,
        appendToReleaseString: String? = null,
        blockSize: String? = null,
        calcMaxImageSize: Boolean = false,
        chainPartition: Boolean = false,
        chainPartitionDoNotUseAb: Boolean = false,
        checkAtMostOnce: Boolean = false,
        doNotAppendVbmetaImage: Boolean = false,
        doNotGenerateFec: Boolean = false,
        doNotUseAb: Boolean = false,
        fecNumRoots: String? = null,
        flags: String? = null,
        hashAlgorithm: String? = null,
        help: Boolean = false,
        image: String? = null,
        includeDescriptorsFromImage: String? = null,
        kernelCmdline: String? = null,
        key: String? = null,
        noHashtree: Boolean = false,
        outputVbmetaImage: String? = null,
        partitionName: String? = null,
        partitionSize: String? = null,
        printRequiredLibavbVersion: Boolean = false,
        prop: Boolean = false,
        propFromFile: Boolean = false,
        publicKeyMetadata: String? = null,
        rollbackIndex: String? = null,
        rollbackIndexLocation: String? = null,
        salt: String? = null,
        setHashtreeDisabledFlag: Boolean = false,
        setVerificationDisabledFlag: Boolean = false,
        setupAsRootfsFromKernel: Boolean = false,
        setupRootfsFromKernel: Boolean = false,
        signingHelper: String? = null,
        signingHelperWithFiles: String? = null,
        usePersistentDigest: Boolean = false
    ): Long? {
        val command = AddHashtreeFooterCommand(
            algorithm = algorithm,
            appendToReleaseString = appendToReleaseString,
            blockSize = blockSize,
            calcMaxImageSize = calcMaxImageSize,
            chainPartition = chainPartition,
            chainPartitionDoNotUseAb = chainPartitionDoNotUseAb,
            checkAtMostOnce = checkAtMostOnce,
            doNotAppendVbmetaImage = doNotAppendVbmetaImage,
            doNotGenerateFec = doNotGenerateFec,
            doNotUseAb = doNotUseAb,
            fecNumRoots = fecNumRoots,
            flags = flags,
            hashAlgorithm = hashAlgorithm,
            help = help,
            image = image,
            includeDescriptorsFromImage = includeDescriptorsFromImage,
            kernelCmdline = kernelCmdline,
            key = key,
            noHashtree = noHashtree,
            outputVbmetaImage = outputVbmetaImage,
            partitionName = partitionName,
            partitionSize = partitionSize,
            printRequiredLibavbVersion = printRequiredLibavbVersion,
            prop = prop,
            propFromFile = propFromFile,
            publicKeyMetadata = publicKeyMetadata,
            rollbackIndex = rollbackIndex,
            rollbackIndexLocation = rollbackIndexLocation,
            salt = salt,
            setHashtreeDisabledFlag = setHashtreeDisabledFlag,
            setVerificationDisabledFlag = setVerificationDisabledFlag,
            setupAsRootfsFromKernel = setupAsRootfsFromKernel,
            setupRootfsFromKernel = setupRootfsFromKernel,
            signingHelper = signingHelper,
            signingHelperWithFiles = signingHelperWithFiles,
            usePersistentDigest = usePersistentDigest
        )
        return repository.execute(command, context)
    }
}
