// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ExtractVbmetaImageUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        help: Boolean = false,
        image: String? = null,
        output: String? = null,
        paddingSize: String? = null
    ): Unit {
        val command = ExtractVbmetaImageCommand(
            help = help,
            image = image,
            output = output,
            paddingSize = paddingSize
        )
        return repository.execute(command, context)
    }
}
