// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class InfoImageUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        cert: Boolean = false,
        help: Boolean = false,
        image: String? = null,
        output: String? = null,
        outputPubkey: String? = null
    ): io.ltirom.tooling.core.AvbImageInfo {
        val command = InfoImageCommand(
            cert = cert,
            help = help,
            image = image,
            output = output,
            outputPubkey = outputPubkey
        )
        return repository.execute(command, context)
    }
}
