// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class ResignImageCommand(
    public val algorithm: String? = null,
    public val autoResize: Boolean = false,
    public val help: Boolean = false,
    public val image: String? = null,
    public val key: String? = null,
    public val signingHelper: String? = null,
    public val signingHelperWithFiles: File? = null
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.AVBTOOL
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("resign_image")
        algorithm?.let { val value = it
            args.add("--algorithm")
            args.add(value.toString())
        }
        if (autoResize) args.add("--auto_resize")
        if (help) args.add("--help")
        image?.let { val value = it
            args.add("--image")
            args.add(value.toString())
        }
        key?.let { val value = it
            args.add("--key")
            args.add(value.toString())
        }
        signingHelper?.let { val value = it
            args.add("--signing_helper")
            args.add(value.toString())
        }
        signingHelperWithFiles?.let { val value = it
            args.add("--signing_helper_with_files")
            args.add(value.toString())
        }
        return args
    }
}
