// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class SetAbMetadataUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        help: Boolean = false,
        miscImage: String? = null,
        slotData: String? = null
    ): Unit {
        val command = SetAbMetadataCommand(
            help = help,
            miscImage = miscImage,
            slotData = slotData
        )
        return repository.execute(command, context)
    }
}
