// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class UpdatePartitionDescriptorCommand(
    public val algorithm: String? = null,
    public val appendToReleaseString: String? = null,
    public val chainPartition: Boolean = false,
    public val chainPartitionDoNotUseAb: Boolean = false,
    public val flags: String? = null,
    public val help: Boolean = false,
    public val image: String? = null,
    public val includeDescriptorsFromImage: String? = null,
    public val kernelCmdline: String? = null,
    public val key: String? = null,
    public val output: String? = null,
    public val partitionImage: String? = null,
    public val printRequiredLibavbVersion: Boolean = false,
    public val prop: Boolean = false,
    public val propFromFile: Boolean = false,
    public val publicKeyMetadata: String? = null,
    public val rollbackIndex: String? = null,
    public val rollbackIndexLocation: String? = null,
    public val setHashtreeDisabledFlag: Boolean = false,
    public val setVerificationDisabledFlag: Boolean = false,
    public val setupRootfsFromKernel: Boolean = false,
    public val signingHelper: String? = null,
    public val signingHelperWithFiles: String? = null
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.AVBTOOL
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("update_partition_descriptor")
        algorithm?.let { val value = it
            args.add("--algorithm")
            args.add(value.toString())
        }
        appendToReleaseString?.let { val value = it
            args.add("--append_to_release_string")
            args.add(value.toString())
        }
        if (chainPartition) args.add("--chain_partition")
        if (chainPartitionDoNotUseAb) args.add("--chain_partition_do_not_use_ab")
        flags?.let { val value = it
            args.add("--flags")
            args.add(value.toString())
        }
        if (help) args.add("--help")
        image?.let { val value = it
            args.add("--image")
            args.add(value.toString())
        }
        includeDescriptorsFromImage?.let { val value = it
            args.add("--include_descriptors_from_image")
            args.add(value.toString())
        }
        kernelCmdline?.let { val value = it
            args.add("--kernel_cmdline")
            args.add(value.toString())
        }
        key?.let { val value = it
            args.add("--key")
            args.add(value.toString())
        }
        output?.let { val value = it
            args.add("--output")
            args.add(value.toString())
        }
        partitionImage?.let { val value = it
            args.add("--partition_image")
            args.add(value.toString())
        }
        if (printRequiredLibavbVersion) args.add("--print_required_libavb_version")
        if (prop) args.add("--prop")
        if (propFromFile) args.add("--prop_from_file")
        publicKeyMetadata?.let { val value = it
            args.add("--public_key_metadata")
            args.add(value.toString())
        }
        rollbackIndex?.let { val value = it
            args.add("--rollback_index")
            args.add(value.toString())
        }
        rollbackIndexLocation?.let { val value = it
            args.add("--rollback_index_location")
            args.add(value.toString())
        }
        if (setHashtreeDisabledFlag) args.add("--set_hashtree_disabled_flag")
        if (setVerificationDisabledFlag) args.add("--set_verification_disabled_flag")
        if (setupRootfsFromKernel) args.add("--setup_rootfs_from_kernel")
        signingHelper?.let { val value = it
            args.add("--signing_helper")
            args.add(value.toString())
        }
        signingHelperWithFiles?.let { val value = it
            args.add("--signing_helper_with_files")
            args.add(value.toString())
        }
        return args
    }
}
