// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.avbtool

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class UpdatePartitionDescriptorUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        algorithm: String? = null,
        appendToReleaseString: String? = null,
        chainPartition: Boolean = false,
        chainPartitionDoNotUseAb: Boolean = false,
        flags: String? = null,
        help: Boolean = false,
        image: String? = null,
        includeDescriptorsFromImage: String? = null,
        kernelCmdline: String? = null,
        key: String? = null,
        output: String? = null,
        partitionImage: String? = null,
        printRequiredLibavbVersion: Boolean = false,
        prop: Boolean = false,
        propFromFile: Boolean = false,
        publicKeyMetadata: String? = null,
        rollbackIndex: String? = null,
        rollbackIndexLocation: String? = null,
        setHashtreeDisabledFlag: Boolean = false,
        setVerificationDisabledFlag: Boolean = false,
        setupRootfsFromKernel: Boolean = false,
        signingHelper: String? = null,
        signingHelperWithFiles: String? = null
    ): Unit {
        val command = UpdatePartitionDescriptorCommand(
            algorithm = algorithm,
            appendToReleaseString = appendToReleaseString,
            chainPartition = chainPartition,
            chainPartitionDoNotUseAb = chainPartitionDoNotUseAb,
            flags = flags,
            help = help,
            image = image,
            includeDescriptorsFromImage = includeDescriptorsFromImage,
            kernelCmdline = kernelCmdline,
            key = key,
            output = output,
            partitionImage = partitionImage,
            printRequiredLibavbVersion = printRequiredLibavbVersion,
            prop = prop,
            propFromFile = propFromFile,
            publicKeyMetadata = publicKeyMetadata,
            rollbackIndex = rollbackIndex,
            rollbackIndexLocation = rollbackIndexLocation,
            setHashtreeDisabledFlag = setHashtreeDisabledFlag,
            setVerificationDisabledFlag = setVerificationDisabledFlag,
            setupRootfsFromKernel = setupRootfsFromKernel,
            signingHelper = signingHelper,
            signingHelperWithFiles = signingHelperWithFiles
        )
        return repository.execute(command, context)
    }
}
