// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.make_f2fs

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ExecuteUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        B: String? = null,
        C: List<String> = emptyList(),
        D: String? = null,
        E: String? = null,
        F: Boolean = false,
        G: String? = null,
        H: Boolean = false,
        I: Boolean = false,
        L: String? = null,
        M: Boolean = false,
        O: String? = null,
        Q: Boolean = false,
        R: Boolean = false,
        S: String? = null,
        T: String? = null,
        U: String? = null,
        V: Boolean = false,
        W: String? = null,
        Z: String? = null,
        positionalArgs: List<String> = emptyList()
    ): String {
        val command = ExecuteCommand(
            B = B,
            C = C,
            D = D,
            E = E,
            F = F,
            G = G,
            H = H,
            I = I,
            L = L,
            M = M,
            O = O,
            Q = Q,
            R = R,
            S = S,
            T = T,
            U = U,
            V = V,
            W = W,
            Z = Z,
            positionalArgs = positionalArgs
        )
        return repository.execute(command, context)
    }
}
