// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.lpflash.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.lpflash.*
import java.io.File

public class LpflashCliCommand(
    private val useCase: ExecuteUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "lpflash") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ExecuteUseCase(repository), context)

    override fun help(context: Context): String = "Execute the tool with its options and positional operands"

    public val positionalArgs: List<String> by argument(name = "positionalArgs", help = "Tool-specific positional operands").multiple()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                positionalArgs = positionalArgs
            )
        }
    }
}
