// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.aapt2

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class CompileUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        O: Boolean = false,
        V: Boolean = false,
        dir: Boolean = false,
        featureFlags: Boolean = false,
        filterProduct: Boolean = false,
        help: Boolean = false,
        legacy: Boolean = false,
        noCrunch: Boolean = false,
        outputTextSymbols: Boolean = false,
        pngCompressionLevel: Boolean = false,
        preserveVisibilityOfStyleables: Boolean = false,
        pseudoLocalize: Boolean = false,
        pseudoLocalizeGenderRatio: Boolean = false,
        pseudoLocalizeGenderValues: Boolean = false,
        sourcePath: Boolean = false,
        traceFolder: Boolean = false,
        visibility: Boolean = false,
        zip: Boolean = false
    ): Unit {
        val command = CompileCommand(
            O = O,
            V = V,
            dir = dir,
            featureFlags = featureFlags,
            filterProduct = filterProduct,
            help = help,
            legacy = legacy,
            noCrunch = noCrunch,
            outputTextSymbols = outputTextSymbols,
            pngCompressionLevel = pngCompressionLevel,
            preserveVisibilityOfStyleables = preserveVisibilityOfStyleables,
            pseudoLocalize = pseudoLocalize,
            pseudoLocalizeGenderRatio = pseudoLocalizeGenderRatio,
            pseudoLocalizeGenderValues = pseudoLocalizeGenderValues,
            sourcePath = sourcePath,
            traceFolder = traceFolder,
            visibility = visibility,
            zip = zip
        )
        return repository.execute(command, context)
    }
}
