// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.aapt2

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class CompileCommand(
    public val O: Boolean = false,
    public val V: Boolean = false,
    public val dir: Boolean = false,
    public val featureFlags: Boolean = false,
    public val filterProduct: Boolean = false,
    public val help: Boolean = false,
    public val legacy: Boolean = false,
    public val noCrunch: Boolean = false,
    public val outputTextSymbols: Boolean = false,
    public val pngCompressionLevel: Boolean = false,
    public val preserveVisibilityOfStyleables: Boolean = false,
    public val pseudoLocalize: Boolean = false,
    public val pseudoLocalizeGenderRatio: Boolean = false,
    public val pseudoLocalizeGenderValues: Boolean = false,
    public val sourcePath: Boolean = false,
    public val traceFolder: Boolean = false,
    public val visibility: Boolean = false,
    public val zip: Boolean = false
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.AAPT2
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("compile")
        if (O) args.add("-o")
        if (V) args.add("-v")
        if (dir) args.add("--dir")
        if (featureFlags) args.add("--feature-flags")
        if (filterProduct) args.add("--filter-product")
        if (help) args.add("--help")
        if (legacy) args.add("--legacy")
        if (noCrunch) args.add("--no-crunch")
        if (outputTextSymbols) args.add("--output-text-symbols")
        if (pngCompressionLevel) args.add("--png-compression-level")
        if (preserveVisibilityOfStyleables) args.add("--preserve-visibility-of-styleables")
        if (pseudoLocalize) args.add("--pseudo-localize")
        if (pseudoLocalizeGenderRatio) args.add("--pseudo-localize-gender-ratio")
        if (pseudoLocalizeGenderValues) args.add("--pseudo-localize-gender-values")
        if (sourcePath) args.add("--source-path")
        if (traceFolder) args.add("--trace-folder")
        if (visibility) args.add("--visibility")
        if (zip) args.add("--zip")
        return args
    }
}
