// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.aapt2

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class ConvertCommand(
    public val O: Boolean = false,
    public val V: Boolean = false,
    public val collapseResourceNames: Boolean = false,
    public val deduplicateEntryValues: Boolean = false,
    public val enableCompactEntries: Boolean = false,
    public val enableSparseEncoding: Boolean = false,
    public val forceSparseEncoding: Boolean = false,
    public val help: Boolean = false,
    public val keepRawValues: Boolean = false,
    public val outputFormat: Boolean = false,
    public val resourcesConfigPath: Boolean = false
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.AAPT2
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("convert")
        if (O) args.add("-o")
        if (V) args.add("-v")
        if (collapseResourceNames) args.add("--collapse-resource-names")
        if (deduplicateEntryValues) args.add("--deduplicate-entry-values")
        if (enableCompactEntries) args.add("--enable-compact-entries")
        if (enableSparseEncoding) args.add("--enable-sparse-encoding")
        if (forceSparseEncoding) args.add("--force-sparse-encoding")
        if (help) args.add("--help")
        if (keepRawValues) args.add("--keep-raw-values")
        if (outputFormat) args.add("--output-format")
        if (resourcesConfigPath) args.add("--resources-config-path")
        return args
    }
}
