// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.aapt2

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class DumpResourcesUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        V: Boolean = false,
        help: Boolean = false,
        noValues: Boolean = false
    ): Unit {
        val command = DumpResourcesCommand(
            V = V,
            help = help,
            noValues = noValues
        )
        return repository.execute(command, context)
    }
}
