// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.aapt2

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class LinkCommand(
    public val A: Boolean = false,
    public val C: Boolean = false,
    public val E: Boolean = false,
    public val I: Boolean = false,
    public val O: Boolean = false,
    public val R: Boolean = false,
    public val V: Boolean = false,
    public val X: Boolean = false,
    public val Z: Boolean = false,
    public val addJavadocAnnotation: Boolean = false,
    public val allowReservedPackageId: Boolean = false,
    public val autoAddOverlay: Boolean = false,
    public val compileSdkVersionCode: Boolean = false,
    public val compileSdkVersionName: Boolean = false,
    public val customPackage: Boolean = false,
    public val debugMode: Boolean = false,
    public val emitIds: Boolean = false,
    public val enableCompactEntries: Boolean = false,
    public val enableSparseEncoding: Boolean = false,
    public val excludeConfigs: Boolean = false,
    public val excludeSources: Boolean = false,
    public val extraPackages: Boolean = false,
    public val featureFlags: Boolean = false,
    public val fingerprintPrefix: Boolean = false,
    public val help: Boolean = false,
    public val java: Boolean = false,
    public val keepRawValues: Boolean = false,
    public val manifest: Boolean = false,
    public val mergeOnly: Boolean = false,
    public val minSdkVersion: Boolean = false,
    public val noAutoVersion: Boolean = false,
    public val noCompileSdkMetadata: Boolean = false,
    public val noCompress: Boolean = false,
    public val noCompressFonts: Boolean = false,
    public val noCompressRegex: Boolean = false,
    public val noProguardLocationReference: Boolean = false,
    public val noResourceDeduping: Boolean = false,
    public val noResourceRemoval: Boolean = false,
    public val noStaticLibPackages: Boolean = false,
    public val noVersionTransitions: Boolean = false,
    public val noVersionVectors: Boolean = false,
    public val noXmlNamespaces: Boolean = false,
    public val nonFinalIds: Boolean = false,
    public val nonUpdatableSystem: Boolean = false,
    public val outputTextSymbols: Boolean = false,
    public val outputToDir: Boolean = false,
    public val overrideStylesInsteadOfOverlaying: Boolean = false,
    public val packageId: Boolean = false,
    public val preferredDensity: Boolean = false,
    public val privateSymbols: Boolean = false,
    public val product: Boolean = false,
    public val proguard: Boolean = false,
    public val proguardConditionalKeepRules: Boolean = false,
    public val proguardMainDex: Boolean = false,
    public val proguardMinimalKeepRules: Boolean = false,
    public val protoFormat: Boolean = false,
    public val renameInstrumentationTargetPackage: Boolean = false,
    public val renameManifestPackage: Boolean = false,
    public val renameOverlayCategory: Boolean = false,
    public val renameOverlayTargetPackage: Boolean = false,
    public val renameResourcesPackage: Boolean = false,
    public val replaceVersion: Boolean = false,
    public val revisionCode: Boolean = false,
    public val sharedLib: Boolean = false,
    public val split: Boolean = false,
    public val stableIds: Boolean = false,
    public val staticLib: Boolean = false,
    public val strictVisibility: Boolean = false,
    public val targetSdkVersion: Boolean = false,
    public val traceFolder: Boolean = false,
    public val value0: Boolean = false,
    public val versionCode: Boolean = false,
    public val versionCodeMajor: Boolean = false,
    public val versionName: Boolean = false,
    public val warnManifestValidation: Boolean = false
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.AAPT2
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("link")
        if (A) args.add("-A")
        if (C) args.add("-c")
        if (E) args.add("-e")
        if (I) args.add("-I")
        if (O) args.add("-o")
        if (R) args.add("-R")
        if (V) args.add("-v")
        if (X) args.add("-x")
        if (Z) args.add("-z")
        if (addJavadocAnnotation) args.add("--add-javadoc-annotation")
        if (allowReservedPackageId) args.add("--allow-reserved-package-id")
        if (autoAddOverlay) args.add("--auto-add-overlay")
        if (compileSdkVersionCode) args.add("--compile-sdk-version-code")
        if (compileSdkVersionName) args.add("--compile-sdk-version-name")
        if (customPackage) args.add("--custom-package")
        if (debugMode) args.add("--debug-mode")
        if (emitIds) args.add("--emit-ids")
        if (enableCompactEntries) args.add("--enable-compact-entries")
        if (enableSparseEncoding) args.add("--enable-sparse-encoding")
        if (excludeConfigs) args.add("--exclude-configs")
        if (excludeSources) args.add("--exclude-sources")
        if (extraPackages) args.add("--extra-packages")
        if (featureFlags) args.add("--feature-flags")
        if (fingerprintPrefix) args.add("--fingerprint-prefix")
        if (help) args.add("--help")
        if (java) args.add("--java")
        if (keepRawValues) args.add("--keep-raw-values")
        if (manifest) args.add("--manifest")
        if (mergeOnly) args.add("--merge-only")
        if (minSdkVersion) args.add("--min-sdk-version")
        if (noAutoVersion) args.add("--no-auto-version")
        if (noCompileSdkMetadata) args.add("--no-compile-sdk-metadata")
        if (noCompress) args.add("--no-compress")
        if (noCompressFonts) args.add("--no-compress-fonts")
        if (noCompressRegex) args.add("--no-compress-regex")
        if (noProguardLocationReference) args.add("--no-proguard-location-reference")
        if (noResourceDeduping) args.add("--no-resource-deduping")
        if (noResourceRemoval) args.add("--no-resource-removal")
        if (noStaticLibPackages) args.add("--no-static-lib-packages")
        if (noVersionTransitions) args.add("--no-version-transitions")
        if (noVersionVectors) args.add("--no-version-vectors")
        if (noXmlNamespaces) args.add("--no-xml-namespaces")
        if (nonFinalIds) args.add("--non-final-ids")
        if (nonUpdatableSystem) args.add("--non-updatable-system")
        if (outputTextSymbols) args.add("--output-text-symbols")
        if (outputToDir) args.add("--output-to-dir")
        if (overrideStylesInsteadOfOverlaying) args.add("--override-styles-instead-of-overlaying")
        if (packageId) args.add("--package-id")
        if (preferredDensity) args.add("--preferred-density")
        if (privateSymbols) args.add("--private-symbols")
        if (product) args.add("--product")
        if (proguard) args.add("--proguard")
        if (proguardConditionalKeepRules) args.add("--proguard-conditional-keep-rules")
        if (proguardMainDex) args.add("--proguard-main-dex")
        if (proguardMinimalKeepRules) args.add("--proguard-minimal-keep-rules")
        if (protoFormat) args.add("--proto-format")
        if (renameInstrumentationTargetPackage) args.add("--rename-instrumentation-target-package")
        if (renameManifestPackage) args.add("--rename-manifest-package")
        if (renameOverlayCategory) args.add("--rename-overlay-category")
        if (renameOverlayTargetPackage) args.add("--rename-overlay-target-package")
        if (renameResourcesPackage) args.add("--rename-resources-package")
        if (replaceVersion) args.add("--replace-version")
        if (revisionCode) args.add("--revision-code")
        if (sharedLib) args.add("--shared-lib")
        if (split) args.add("--split")
        if (stableIds) args.add("--stable-ids")
        if (staticLib) args.add("--static-lib")
        if (strictVisibility) args.add("--strict-visibility")
        if (targetSdkVersion) args.add("--target-sdk-version")
        if (traceFolder) args.add("--trace-folder")
        if (value0) args.add("-0")
        if (versionCode) args.add("--version-code")
        if (versionCodeMajor) args.add("--version-code-major")
        if (versionName) args.add("--version-name")
        if (warnManifestValidation) args.add("--warn-manifest-validation")
        return args
    }
}
