// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.dumperofs

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class ExecuteCommand(
    public val E: Boolean = false,
    public val S: Boolean = false,
    public val cat: Boolean = false,
    public val device: String? = null,
    public val help: Boolean = false,
    public val ls: Boolean = false,
    public val nid: String? = null,
    public val offset: String? = null,
    public val path: String? = null,
    public val version: Boolean = false,
    public val positionalArgs: List<String> = emptyList()
) : ToolCommand<io.ltirom.tooling.core.ParsedToolMetadata> {

    override val toolId: ToolId get() = ToolId.DUMP_EROFS
    override val risk: ToolRisk get() = ToolRisk.READ_ONLY
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<io.ltirom.tooling.core.ParsedToolMetadata> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("metadata") as io.ltirom.tooling.core.ToolOutputParser<io.ltirom.tooling.core.ParsedToolMetadata>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): io.ltirom.tooling.core.ParsedToolMetadata {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        if (E) args.add("-e")
        if (S) args.add("-S")
        if (cat) args.add("--cat")
        device?.let { val value = it
            args.add("--device")
            args.add(value.toString())
        }
        if (help) args.add("--help")
        if (ls) args.add("--ls")
        nid?.let { val value = it
            args.add("--nid")
            args.add(value.toString())
        }
        offset?.let { val value = it
            args.add("--offset")
            args.add(value.toString())
        }
        path?.let { val value = it
            args.add("--path")
            args.add(value.toString())
        }
        if (version) args.add("--version")
        for (item in positionalArgs) {
            args.add(item.toString())
        }
        return args
    }
}
