// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.dumperofs

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ExecuteUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        E: Boolean = false,
        S: Boolean = false,
        cat: Boolean = false,
        device: String? = null,
        help: Boolean = false,
        ls: Boolean = false,
        nid: String? = null,
        offset: String? = null,
        path: String? = null,
        version: Boolean = false,
        positionalArgs: List<String> = emptyList()
    ): io.ltirom.tooling.core.ParsedToolMetadata {
        val command = ExecuteCommand(
            E = E,
            S = S,
            cat = cat,
            device = device,
            help = help,
            ls = ls,
            nid = nid,
            offset = offset,
            path = path,
            version = version,
            positionalArgs = positionalArgs
        )
        return repository.execute(command, context)
    }
}
