// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.mkdtboimg.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.mkdtboimg.*
import java.io.File

public class CfgCreateCliCommand(
    private val useCase: CfgCreateUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "cfg_create") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(CfgCreateUseCase(repository), context)

    override fun help(context: Context): String = "usage: cfg_create [-h] [--dtb-dir [DTBDIR]] [conf_file]"

    public val dtbDir: Boolean by option("--dtb-dir", help = "[DTBDIR], -d [DTBDIR]").flag()
    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                dtbDir = dtbDir,
                help = help
            )
        }
    }
}
