// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.apktool

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class BuildUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        aapt: File? = null,
        all: Boolean = false,
        allSrc: Boolean = false,
        copyOriginal: Boolean = false,
        debuggable: Boolean = false,
        force: Boolean = false,
        framePath: File? = null,
        frameTag: String? = null,
        ignoreRawValues: Boolean = false,
        jobs: Int? = null,
        keepBrokenRes: Boolean = false,
        lib: List<String> = emptyList(),
        matchOriginal: Boolean = false,
        netSecConf: Boolean = false,
        noApk: Boolean = false,
        noAssets: Boolean = false,
        noCrunch: Boolean = false,
        noDebugInfo: Boolean = false,
        noRes: Boolean = false,
        noSrc: Boolean = false,
        onlyManifest: Boolean = false,
        output: File? = null,
        quiet: Boolean = false,
        resResolveMode: String? = null,
        verbose: Boolean = false,
        apkDir: File
    ): Unit {
        val command = BuildCommand(
            aapt = aapt,
            all = all,
            allSrc = allSrc,
            copyOriginal = copyOriginal,
            debuggable = debuggable,
            force = force,
            framePath = framePath,
            frameTag = frameTag,
            ignoreRawValues = ignoreRawValues,
            jobs = jobs,
            keepBrokenRes = keepBrokenRes,
            lib = lib,
            matchOriginal = matchOriginal,
            netSecConf = netSecConf,
            noApk = noApk,
            noAssets = noAssets,
            noCrunch = noCrunch,
            noDebugInfo = noDebugInfo,
            noRes = noRes,
            noSrc = noSrc,
            onlyManifest = onlyManifest,
            output = output,
            quiet = quiet,
            resResolveMode = resResolveMode,
            verbose = verbose,
            apkDir = apkDir
        )
        return repository.execute(command, context)
    }
}
