// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.apktool

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class DecodeCommand(
    public val aapt: File? = null,
    public val all: Boolean = false,
    public val allSrc: Boolean = false,
    public val copyOriginal: Boolean = false,
    public val debuggable: Boolean = false,
    public val force: Boolean = false,
    public val framePath: File? = null,
    public val frameTag: String? = null,
    public val ignoreRawValues: Boolean = false,
    public val jobs: Int? = null,
    public val keepBrokenRes: Boolean = false,
    public val lib: List<String> = emptyList(),
    public val matchOriginal: Boolean = false,
    public val netSecConf: Boolean = false,
    public val noApk: Boolean = false,
    public val noAssets: Boolean = false,
    public val noCrunch: Boolean = false,
    public val noDebugInfo: Boolean = false,
    public val noRes: Boolean = false,
    public val noSrc: Boolean = false,
    public val onlyManifest: Boolean = false,
    public val output: File? = null,
    public val quiet: Boolean = false,
    public val resResolveMode: String? = null,
    public val verbose: Boolean = false,
    public val apkFile: File
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.APKTOOL
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("decode")
        aapt?.let { val value = it
            args.add("--aapt")
            args.add(value.toString())
        }
        if (all) args.add("--all")
        if (allSrc) args.add("--all-src")
        if (copyOriginal) args.add("--copy-original")
        if (debuggable) args.add("--debuggable")
        if (force) args.add("--force")
        framePath?.let { val value = it
            args.add("--frame-path")
            args.add(value.toString())
        }
        frameTag?.let { val value = it
            args.add("--frame-tag")
            args.add(value.toString())
        }
        if (ignoreRawValues) args.add("--ignore-raw-values")
        jobs?.let { val value = it
            args.add("--jobs")
            args.add(value.toString())
        }
        if (keepBrokenRes) args.add("--keep-broken-res")
        for (item in lib) {
            args.add("--lib")
            args.add(item.toString())
        }
        if (matchOriginal) args.add("--match-original")
        if (netSecConf) args.add("--net-sec-conf")
        if (noApk) args.add("--no-apk")
        if (noAssets) args.add("--no-assets")
        if (noCrunch) args.add("--no-crunch")
        if (noDebugInfo) args.add("--no-debug-info")
        if (noRes) args.add("--no-res")
        if (noSrc) args.add("--no-src")
        if (onlyManifest) args.add("--only-manifest")
        output?.let { val value = it
            args.add("--output")
            args.add(value.toString())
        }
        if (quiet) args.add("--quiet")
        resResolveMode?.let { val value = it
            args.add("--res-resolve-mode")
            args.add(value.toString())
        }
        if (verbose) args.add("--verbose")
        args.add(apkFile.toString())
        return args
    }
}
