// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.mkfserofs.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.mkfserofs.*
import java.io.File

public class MkfserofsCliCommand(
    private val useCase: ExecuteUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "mkfs.erofs") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ExecuteUseCase(repository), context)

    override fun help(context: Context): String = "Execute the tool with its options and positional operands"

    public val B: String? by option("--b", "-b", help = "set block size to # (# = page size by default)")
    public val C: String? by option("--c", "-C", help = "specify the size of compress physical cluster in bytes")
    public val D: String? by option("--d", "-d", help = "set output verbosity; 0=quiet, 9=verbose (default=2)")
    public val E: String? by option("--e", "-E", help = "[,...]             X=extended options")
    public val L: String? by option("--l", "-L", help = "set the volume label (maximum 15 bytes)")
    public val T: String? by option("--t", "-T", help = "specify a fixed UNIX timestamp # as build time")
    public val U: String? by option("--u", "-U", help = "use a given filesystem UUID")
    public val X: String? by option("--x", "-x", help = "set xattr tolerance to # (< 0, disable xattrs; default 2)")
    public val Z: String? by option("--z", "-z", help = "[,level=Y]         X=compressor (Y=compression level, Z=dictionary size, optional)")
    public val allRoot: Boolean by option("--all-root", help = "make all files owned by root").flag()
    public val allTime: Boolean by option("--all-time", help = "the timestamp is also applied to all files (default)").flag()
    public val aufs: Boolean by option("--aufs", help = "replace aufs special files with overlayfs metadata").flag()
    public val blobdev: String? by option("--blobdev", help = "specify an extra device X to store chunked data")
    public val blockListFile: String? by option("--block-list-file", help = "X=block_list file")
    public val chunksize: String? by option("--chunksize", help = "generate chunk-based files with #-byte chunks")
    public val clean: String? by option("--clean", help = "run full clean build (default) or:")
    public val compressHints: String? by option("--compress-hints", help = "specify a file to configure per-file compression strategy")
    public val excludePath: String? by option("--exclude-path", help = "avoid including file X (X = exact literal path)")
    public val excludeRegex: String? by option("--exclude-regex", help = "avoid including files that match X (X = regular expression)")
    public val fileContexts: String? by option("--file-contexts", help = "specify a file contexts file to setup selinux labels")
    public val forceGid: String? by option("--force-gid", help = "set all file gids to # (# = GID)")
    public val forceUid: String? by option("--force-uid", help = "set all file uids to # (# = UID)")
    public val fsConfigFile: String? by option("--fs-config-file", help = "X=fs_config file")
    public val gidOffset: String? by option("--gid-offset", help = "add offset # to all file gids (# = id offset)")
    public val hardDereference: Boolean by option("--hard-dereference", help = "dereference hardlinks, add links as separate inodes").flag()
    public val help: Boolean by option("--help", "-h", help = "display this help and exit").flag()
    public val ignoreMtime: Boolean by option("--ignore-mtime", help = "use build time instead of strict per-file modification time").flag()
    public val incremental: String? by option("--incremental", help = "run incremental build")
    public val maxExtentBytes: String? by option("--max-extent-bytes", help = "set maximum decompressed extent size # in bytes")
    public val mkfsTime: Boolean by option("--mkfs-time", help = "the timestamp is applied as build time only").flag()
    public val mountPoint: String? by option("--mount-point", help = "X=prefix of target fs path (default: /)")
    public val offset: String? by option("--offset", help = "skip # bytes at the beginning of IMAGE.")
    public val ovlfsStrip: String? by option("--ovlfs-strip", help = "strip overlayfs metadata in the target image (e.g. whiteouts)")
    public val preserveMtime: Boolean by option("--preserve-mtime", help = "keep per-file modification time strictly").flag()
    public val productOut: String? by option("--product-out", help = "X=product_out directory")
    public val quiet: Boolean by option("--quiet", help = "quiet execution (do not write anything to standard output.)").flag()
    public val rootXattrIsize: String? by option("--root-xattr-isize", help = "ensure the inline xattr size of the root directory is # bytes at least")
    public val sort: File? by option("--sort", help = "data sorting order for tarballs as input (default: path)").convert { File(it) }
    public val tar: String? by option("--tar", help = "generate a full or index-only image from a tarball(-ish) source")
    public val uidOffset: String? by option("--uid-offset", help = "add offset # to all file uids (# = id offset)")
    public val ungzip: String? by option("--ungzip", help = "try to filter the tarball stream through gzip")
    public val unxz: String? by option("--unxz", help = "try to filter the tarball stream through xz/lzma/lzip")
    public val version: Boolean by option("--version", "-V", help = "print the version number of mkfs.erofs and exit").flag()
    public val workers: String? by option("--workers", help = "set the number of worker threads to # (default: 16)")
    public val xattrPrefix: String? by option("--xattr-prefix", help = "X=extra xattr name prefix")
    public val zfeatureBits: String? by option("--zfeature-bits", help = "toggle filesystem compression features according to given bits #")
    public val positionalArgs: List<String> by argument(name = "positionalArgs", help = "Tool-specific positional operands").multiple()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                B = B,
                C = C,
                D = D,
                E = E,
                L = L,
                T = T,
                U = U,
                X = X,
                Z = Z,
                allRoot = allRoot,
                allTime = allTime,
                aufs = aufs,
                blobdev = blobdev,
                blockListFile = blockListFile,
                chunksize = chunksize,
                clean = clean,
                compressHints = compressHints,
                excludePath = excludePath,
                excludeRegex = excludeRegex,
                fileContexts = fileContexts,
                forceGid = forceGid,
                forceUid = forceUid,
                fsConfigFile = fsConfigFile,
                gidOffset = gidOffset,
                hardDereference = hardDereference,
                help = help,
                ignoreMtime = ignoreMtime,
                incremental = incremental,
                maxExtentBytes = maxExtentBytes,
                mkfsTime = mkfsTime,
                mountPoint = mountPoint,
                offset = offset,
                ovlfsStrip = ovlfsStrip,
                preserveMtime = preserveMtime,
                productOut = productOut,
                quiet = quiet,
                rootXattrIsize = rootXattrIsize,
                sort = sort,
                tar = tar,
                uidOffset = uidOffset,
                ungzip = ungzip,
                unxz = unxz,
                version = version,
                workers = workers,
                xattrPrefix = xattrPrefix,
                zfeatureBits = zfeatureBits,
                positionalArgs = positionalArgs
            )
        }
    }
}
