// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class AgentTaskViewUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        follow: Boolean = false,
        help: Boolean = false,
        jq: Boolean = false,
        json: Boolean = false,
        log: Boolean = false,
        repo: Boolean = false,
        template: Boolean = false,
        version: Boolean = false,
        web: Boolean = false
    ): Unit {
        val command = AgentTaskViewCommand(
            follow = follow,
            help = help,
            jq = jq,
            json = json,
            log = log,
            repo = repo,
            template = template,
            version = version,
            web = web
        )
        return repository.execute(command, context)
    }
}
