// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class AgentTaskListUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        help: Boolean = false,
        jq: Boolean = false,
        json: Boolean = false,
        limit: Boolean = false,
        template: Boolean = false,
        version: Boolean = false,
        web: Boolean = false
    ): Unit {
        val command = AgentTaskListCommand(
            help = help,
            jq = jq,
            json = json,
            limit = limit,
            template = template,
            version = version,
            web = web
        )
        return repository.execute(command, context)
    }
}
