// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class AttestationTrustedRootUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        help: Boolean = false,
        hostname: Boolean = false,
        tufRoot: Boolean = false,
        tufUrl: Boolean = false,
        verifyOnly: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = AttestationTrustedRootCommand(
            help = help,
            hostname = hostname,
            tufRoot = tufRoot,
            tufUrl = tufUrl,
            verifyOnly = verifyOnly,
            version = version
        )
        return repository.execute(command, context)
    }
}
