// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class AuthRefreshUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        clipboard: Boolean = false,
        help: Boolean = false,
        hostname: Boolean = false,
        insecureStorage: Boolean = false,
        removeScopes: Boolean = false,
        resetScopes: Boolean = false,
        scopes: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = AuthRefreshCommand(
            clipboard = clipboard,
            help = help,
            hostname = hostname,
            insecureStorage = insecureStorage,
            removeScopes = removeScopes,
            resetScopes = resetScopes,
            scopes = scopes,
            version = version
        )
        return repository.execute(command, context)
    }
}
