// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class AuthStatusUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        active: Boolean = false,
        help: Boolean = false,
        hostname: Boolean = false,
        jq: Boolean = false,
        json: Boolean = false,
        showToken: Boolean = false,
        template: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = AuthStatusCommand(
            active = active,
            help = help,
            hostname = hostname,
            jq = jq,
            json = json,
            showToken = showToken,
            template = template,
            version = version
        )
        return repository.execute(command, context)
    }
}
