// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class AuthLoginCommand(
    public val clipboard: Boolean = false,
    public val gitProtocol: Boolean = false,
    public val help: Boolean = false,
    public val hostname: Boolean = false,
    public val insecureStorage: Boolean = false,
    public val scopes: Boolean = false,
    public val skipSshKey: Boolean = false,
    public val version: Boolean = false,
    public val web: Boolean = false,
    public val withToken: Boolean = false
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.GH
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("auth")
        args.add("login")
        if (clipboard) args.add("--clipboard")
        if (gitProtocol) args.add("--git-protocol")
        if (help) args.add("--help")
        if (hostname) args.add("--hostname")
        if (insecureStorage) args.add("--insecure-storage")
        if (scopes) args.add("--scopes")
        if (skipSshKey) args.add("--skip-ssh-key")
        if (version) args.add("--version")
        if (web) args.add("--web")
        if (withToken) args.add("--with-token")
        return args
    }
}
