// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class AuthLoginUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        clipboard: Boolean = false,
        gitProtocol: Boolean = false,
        help: Boolean = false,
        hostname: Boolean = false,
        insecureStorage: Boolean = false,
        scopes: Boolean = false,
        skipSshKey: Boolean = false,
        version: Boolean = false,
        web: Boolean = false,
        withToken: Boolean = false
    ): Unit {
        val command = AuthLoginCommand(
            clipboard = clipboard,
            gitProtocol = gitProtocol,
            help = help,
            hostname = hostname,
            insecureStorage = insecureStorage,
            scopes = scopes,
            skipSshKey = skipSshKey,
            version = version,
            web = web,
            withToken = withToken
        )
        return repository.execute(command, context)
    }
}
