// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class BrowseCommand(
    public val actions: Boolean = false,
    public val blame: Boolean = false,
    public val branch: Boolean = false,
    public val commit: Boolean = false,
    public val help: Boolean = false,
    public val noBrowser: Boolean = false,
    public val projects: Boolean = false,
    public val releases: Boolean = false,
    public val repo: Boolean = false,
    public val settings: Boolean = false,
    public val version: Boolean = false,
    public val wiki: Boolean = false
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.GH
    override val risk: ToolRisk get() = ToolRisk.READ_ONLY
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("browse")
        if (actions) args.add("--actions")
        if (blame) args.add("--blame")
        if (branch) args.add("--branch")
        if (commit) args.add("--commit")
        if (help) args.add("--help")
        if (noBrowser) args.add("--no-browser")
        if (projects) args.add("--projects")
        if (releases) args.add("--releases")
        if (repo) args.add("--repo")
        if (settings) args.add("--settings")
        if (version) args.add("--version")
        if (wiki) args.add("--wiki")
        return args
    }
}
