// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class CodespaceEditUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        codespace: Boolean = false,
        displayName: Boolean = false,
        help: Boolean = false,
        machine: Boolean = false,
        repo: Boolean = false,
        repoOwner: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = CodespaceEditCommand(
            codespace = codespace,
            displayName = displayName,
            help = help,
            machine = machine,
            repo = repo,
            repoOwner = repoOwner,
            version = version
        )
        return repository.execute(command, context)
    }
}
