// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class CodespaceCpUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        codespace: Boolean = false,
        expand: Boolean = false,
        help: Boolean = false,
        profile: Boolean = false,
        recursive: Boolean = false,
        repo: Boolean = false,
        repoOwner: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = CodespaceCpCommand(
            codespace = codespace,
            expand = expand,
            help = help,
            profile = profile,
            recursive = recursive,
            repo = repo,
            repoOwner = repoOwner,
            version = version
        )
        return repository.execute(command, context)
    }
}
