// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class CompletionUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        help: Boolean = false,
        shell: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = CompletionCommand(
            help = help,
            shell = shell,
            version = version
        )
        return repository.execute(command, context)
    }
}
