// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ExtensionBrowseUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        debug: Boolean = false,
        help: Boolean = false,
        singleColumn: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = ExtensionBrowseCommand(
            debug = debug,
            help = help,
            singleColumn = singleColumn,
            version = version
        )
        return repository.execute(command, context)
    }
}
