// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class GistEditUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        add: Boolean = false,
        desc: Boolean = false,
        filename: Boolean = false,
        help: Boolean = false,
        remove: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = GistEditCommand(
            add = add,
            desc = desc,
            filename = filename,
            help = help,
            remove = remove,
            version = version
        )
        return repository.execute(command, context)
    }
}
