// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class GistViewUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        allowEscapeSequences: Boolean = false,
        filename: Boolean = false,
        files: Boolean = false,
        help: Boolean = false,
        raw: Boolean = false,
        version: Boolean = false,
        web: Boolean = false
    ): Unit {
        val command = GistViewCommand(
            allowEscapeSequences = allowEscapeSequences,
            filename = filename,
            files = files,
            help = help,
            raw = raw,
            version = version,
            web = web
        )
        return repository.execute(command, context)
    }
}
