// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class LabelCreateUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        color: Boolean = false,
        description: Boolean = false,
        force: Boolean = false,
        help: Boolean = false,
        repo: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = LabelCreateCommand(
            color = color,
            description = description,
            force = force,
            help = help,
            repo = repo,
            version = version
        )
        return repository.execute(command, context)
    }
}
