// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ProjectListUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        closed: Boolean = false,
        format: Boolean = false,
        help: Boolean = false,
        jq: Boolean = false,
        limit: Boolean = false,
        owner: Boolean = false,
        template: Boolean = false,
        version: Boolean = false,
        web: Boolean = false
    ): Unit {
        val command = ProjectListCommand(
            closed = closed,
            format = format,
            help = help,
            jq = jq,
            limit = limit,
            owner = owner,
            template = template,
            version = version,
            web = web
        )
        return repository.execute(command, context)
    }
}
