// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ProjectItemListUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        field: Boolean = false,
        fieldId: Boolean = false,
        format: Boolean = false,
        help: Boolean = false,
        jq: Boolean = false,
        limit: Boolean = false,
        owner: Boolean = false,
        query: Boolean = false,
        template: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = ProjectItemListCommand(
            field = field,
            fieldId = fieldId,
            format = format,
            help = help,
            jq = jq,
            limit = limit,
            owner = owner,
            query = query,
            template = template,
            version = version
        )
        return repository.execute(command, context)
    }
}
