// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ProjectCopyUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        drafts: Boolean = false,
        format: Boolean = false,
        help: Boolean = false,
        jq: Boolean = false,
        sourceOwner: Boolean = false,
        targetOwner: Boolean = false,
        template: Boolean = false,
        title: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = ProjectCopyCommand(
            drafts = drafts,
            format = format,
            help = help,
            jq = jq,
            sourceOwner = sourceOwner,
            targetOwner = targetOwner,
            template = template,
            title = title,
            version = version
        )
        return repository.execute(command, context)
    }
}
