// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class RulesetViewUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        help: Boolean = false,
        org: Boolean = false,
        parents: Boolean = false,
        repo: Boolean = false,
        version: Boolean = false,
        web: Boolean = false
    ): Unit {
        val command = RulesetViewCommand(
            help = help,
            org = org,
            parents = parents,
            repo = repo,
            version = version,
            web = web
        )
        return repository.execute(command, context)
    }
}
