// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class RulesetCheckUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        default: Boolean = false,
        help: Boolean = false,
        repo: Boolean = false,
        version: Boolean = false,
        web: Boolean = false
    ): Unit {
        val command = RulesetCheckCommand(
            default = default,
            help = help,
            repo = repo,
            version = version,
            web = web
        )
        return repository.execute(command, context)
    }
}
