// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class RunListUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        all: Boolean = false,
        branch: Boolean = false,
        commit: String? = null,
        created: Boolean = false,
        event: Boolean = false,
        help: Boolean = false,
        jq: Boolean = false,
        json: Boolean = false,
        limit: Boolean = false,
        repo: Boolean = false,
        status: Boolean = false,
        template: Boolean = false,
        user: Boolean = false,
        version: Boolean = false,
        workflow: Boolean = false
    ): Unit {
        val command = RunListCommand(
            all = all,
            branch = branch,
            commit = commit,
            created = created,
            event = event,
            help = help,
            jq = jq,
            json = json,
            limit = limit,
            repo = repo,
            status = status,
            template = template,
            user = user,
            version = version,
            workflow = workflow
        )
        return repository.execute(command, context)
    }
}
