// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class RunViewUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        attempt: Boolean = false,
        exitStatus: Boolean = false,
        help: Boolean = false,
        job: Boolean = false,
        jq: Boolean = false,
        json: Boolean = false,
        log: Boolean = false,
        logFailed: Boolean = false,
        repo: Boolean = false,
        template: Boolean = false,
        verbose: Boolean = false,
        version: Boolean = false,
        web: Boolean = false
    ): Unit {
        val command = RunViewCommand(
            attempt = attempt,
            exitStatus = exitStatus,
            help = help,
            job = job,
            jq = jq,
            json = json,
            log = log,
            logFailed = logFailed,
            repo = repo,
            template = template,
            verbose = verbose,
            version = version,
            web = web
        )
        return repository.execute(command, context)
    }
}
