// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class RunWatchUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        compact: Boolean = false,
        exitStatus: Boolean = false,
        help: Boolean = false,
        interval: Boolean = false,
        repo: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = RunWatchCommand(
            compact = compact,
            exitStatus = exitStatus,
            help = help,
            interval = interval,
            repo = repo,
            version = version
        )
        return repository.execute(command, context)
    }
}
