// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class SearchCodeCommand(
    public val extension: Boolean = false,
    public val filename: Boolean = false,
    public val help: Boolean = false,
    public val jq: Boolean = false,
    public val json: Boolean = false,
    public val language: Boolean = false,
    public val limit: Boolean = false,
    public val match: Boolean = false,
    public val owner: Boolean = false,
    public val repo: Boolean = false,
    public val size: Boolean = false,
    public val template: Boolean = false,
    public val version: Boolean = false,
    public val web: Boolean = false
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.GH
    override val risk: ToolRisk get() = ToolRisk.READ_ONLY
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("search")
        args.add("code")
        if (extension) args.add("--extension")
        if (filename) args.add("--filename")
        if (help) args.add("--help")
        if (jq) args.add("--jq")
        if (json) args.add("--json")
        if (language) args.add("--language")
        if (limit) args.add("--limit")
        if (match) args.add("--match")
        if (owner) args.add("--owner")
        if (repo) args.add("--repo")
        if (size) args.add("--size")
        if (template) args.add("--template")
        if (version) args.add("--version")
        if (web) args.add("--web")
        return args
    }
}
