// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class SearchReposCommand(
    public val archived: Boolean = false,
    public val created: Boolean = false,
    public val followers: Boolean = false,
    public val forks: Boolean = false,
    public val goodFirstIssues: Boolean = false,
    public val help: Boolean = false,
    public val helpWantedIssues: Boolean = false,
    public val includeForks: Boolean = false,
    public val jq: Boolean = false,
    public val json: Boolean = false,
    public val language: Boolean = false,
    public val license: Boolean = false,
    public val limit: Boolean = false,
    public val match: Boolean = false,
    public val numberTopics: Boolean = false,
    public val order: Boolean = false,
    public val owner: Boolean = false,
    public val size: Boolean = false,
    public val sort: Boolean = false,
    public val stars: Boolean = false,
    public val template: Boolean = false,
    public val topic: Boolean = false,
    public val updated: Boolean = false,
    public val version: Boolean = false,
    public val visibility: Boolean = false,
    public val web: Boolean = false
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.GH
    override val risk: ToolRisk get() = ToolRisk.READ_ONLY
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("search")
        args.add("repos")
        if (archived) args.add("--archived")
        if (created) args.add("--created")
        if (followers) args.add("--followers")
        if (forks) args.add("--forks")
        if (goodFirstIssues) args.add("--good-first-issues")
        if (help) args.add("--help")
        if (helpWantedIssues) args.add("--help-wanted-issues")
        if (includeForks) args.add("--include-forks")
        if (jq) args.add("--jq")
        if (json) args.add("--json")
        if (language) args.add("--language")
        if (license) args.add("--license")
        if (limit) args.add("--limit")
        if (match) args.add("--match")
        if (numberTopics) args.add("--number-topics")
        if (order) args.add("--order")
        if (owner) args.add("--owner")
        if (size) args.add("--size")
        if (sort) args.add("--sort")
        if (stars) args.add("--stars")
        if (template) args.add("--template")
        if (topic) args.add("--topic")
        if (updated) args.add("--updated")
        if (version) args.add("--version")
        if (visibility) args.add("--visibility")
        if (web) args.add("--web")
        return args
    }
}
