// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class SearchCodeUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        extension: Boolean = false,
        filename: Boolean = false,
        help: Boolean = false,
        jq: Boolean = false,
        json: Boolean = false,
        language: Boolean = false,
        limit: Boolean = false,
        match: Boolean = false,
        owner: Boolean = false,
        repo: Boolean = false,
        size: Boolean = false,
        template: Boolean = false,
        version: Boolean = false,
        web: Boolean = false
    ): Unit {
        val command = SearchCodeCommand(
            extension = extension,
            filename = filename,
            help = help,
            jq = jq,
            json = json,
            language = language,
            limit = limit,
            match = match,
            owner = owner,
            repo = repo,
            size = size,
            template = template,
            version = version,
            web = web
        )
        return repository.execute(command, context)
    }
}
