// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class SearchCommitsCommand(
    public val author: Boolean = false,
    public val authorDate: Boolean = false,
    public val authorEmail: Boolean = false,
    public val authorName: Boolean = false,
    public val committer: Boolean = false,
    public val committerDate: Boolean = false,
    public val committerEmail: Boolean = false,
    public val committerName: Boolean = false,
    public val hash: Boolean = false,
    public val help: Boolean = false,
    public val jq: Boolean = false,
    public val json: Boolean = false,
    public val limit: Boolean = false,
    public val merge: Boolean = false,
    public val order: Boolean = false,
    public val owner: Boolean = false,
    public val parent: Boolean = false,
    public val repo: Boolean = false,
    public val sort: Boolean = false,
    public val template: Boolean = false,
    public val tree: Boolean = false,
    public val version: Boolean = false,
    public val visibility: Boolean = false,
    public val web: Boolean = false
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.GH
    override val risk: ToolRisk get() = ToolRisk.READ_ONLY
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("search")
        args.add("commits")
        if (author) args.add("--author")
        if (authorDate) args.add("--author-date")
        if (authorEmail) args.add("--author-email")
        if (authorName) args.add("--author-name")
        if (committer) args.add("--committer")
        if (committerDate) args.add("--committer-date")
        if (committerEmail) args.add("--committer-email")
        if (committerName) args.add("--committer-name")
        if (hash) args.add("--hash")
        if (help) args.add("--help")
        if (jq) args.add("--jq")
        if (json) args.add("--json")
        if (limit) args.add("--limit")
        if (merge) args.add("--merge")
        if (order) args.add("--order")
        if (owner) args.add("--owner")
        if (parent) args.add("--parent")
        if (repo) args.add("--repo")
        if (sort) args.add("--sort")
        if (template) args.add("--template")
        if (tree) args.add("--tree")
        if (version) args.add("--version")
        if (visibility) args.add("--visibility")
        if (web) args.add("--web")
        return args
    }
}
