// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class SecretDeleteCommand(
    public val app: Boolean = false,
    public val env: Boolean = false,
    public val help: Boolean = false,
    public val org: Boolean = false,
    public val repo: Boolean = false,
    public val user: Boolean = false,
    public val version: Boolean = false
) : ToolCommand<Unit> {

    override val toolId: ToolId get() = ToolId.GH
    override val risk: ToolRisk get() = ToolRisk.HOST_WRITE
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Unit> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("default") as io.ltirom.tooling.core.ToolOutputParser<Unit>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Unit {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("secret")
        args.add("delete")
        if (app) args.add("--app")
        if (env) args.add("--env")
        if (help) args.add("--help")
        if (org) args.add("--org")
        if (repo) args.add("--repo")
        if (user) args.add("--user")
        if (version) args.add("--version")
        return args
    }
}
