// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class SecretListUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        app: Boolean = false,
        env: Boolean = false,
        help: Boolean = false,
        jq: Boolean = false,
        json: Boolean = false,
        org: Boolean = false,
        repo: Boolean = false,
        template: Boolean = false,
        user: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = SecretListCommand(
            app = app,
            env = env,
            help = help,
            jq = jq,
            json = json,
            org = org,
            repo = repo,
            template = template,
            user = user,
            version = version
        )
        return repository.execute(command, context)
    }
}
