// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class SecretSetUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        app: Boolean = false,
        body: Boolean = false,
        env: Boolean = false,
        envFile: Boolean = false,
        help: Boolean = false,
        noReposSelected: Boolean = false,
        noStore: Boolean = false,
        org: Boolean = false,
        repo: Boolean = false,
        repos: Boolean = false,
        user: Boolean = false,
        version: Boolean = false,
        visibility: Boolean = false
    ): Unit {
        val command = SecretSetCommand(
            app = app,
            body = body,
            env = env,
            envFile = envFile,
            help = help,
            noReposSelected = noReposSelected,
            noStore = noStore,
            org = org,
            repo = repo,
            repos = repos,
            user = user,
            version = version,
            visibility = visibility
        )
        return repository.execute(command, context)
    }
}
