// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class SkillUpdateUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        all: Boolean = false,
        dir: Boolean = false,
        dryRun: Boolean = false,
        force: Boolean = false,
        help: Boolean = false,
        unpin: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = SkillUpdateCommand(
            all = all,
            dir = dir,
            dryRun = dryRun,
            force = force,
            help = help,
            unpin = unpin,
            version = version
        )
        return repository.execute(command, context)
    }
}
