// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class SkillPublishUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        dryRun: Boolean = false,
        fix: Boolean = false,
        help: Boolean = false,
        tag: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = SkillPublishCommand(
            dryRun = dryRun,
            fix = fix,
            help = help,
            tag = tag,
            version = version
        )
        return repository.execute(command, context)
    }
}
