// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class SkillInstallUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        agent: Boolean = false,
        all: Boolean = false,
        allowHiddenDirs: Boolean = false,
        dir: Boolean = false,
        force: Boolean = false,
        fromLocal: Boolean = false,
        help: Boolean = false,
        pin: Boolean = false,
        scope: Boolean = false,
        upstream: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = SkillInstallCommand(
            agent = agent,
            all = all,
            allowHiddenDirs = allowHiddenDirs,
            dir = dir,
            force = force,
            fromLocal = fromLocal,
            help = help,
            pin = pin,
            scope = scope,
            upstream = upstream,
            version = version
        )
        return repository.execute(command, context)
    }
}
