// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class SkillListUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        agent: Boolean = false,
        dir: Boolean = false,
        help: Boolean = false,
        jq: Boolean = false,
        json: Boolean = false,
        scope: Boolean = false,
        template: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = SkillListCommand(
            agent = agent,
            dir = dir,
            help = help,
            jq = jq,
            json = json,
            scope = scope,
            template = template,
            version = version
        )
        return repository.execute(command, context)
    }
}
