// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class SshKeyDeleteUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        help: Boolean = false,
        version: Boolean = false,
        yes: Boolean = false
    ): Unit {
        val command = SshKeyDeleteCommand(
            help = help,
            version = version,
            yes = yes
        )
        return repository.execute(command, context)
    }
}
