// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class SshKeyAddUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        help: Boolean = false,
        title: Boolean = false,
        type: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = SshKeyAddCommand(
            help = help,
            title = title,
            type = type,
            version = version
        )
        return repository.execute(command, context)
    }
}
