// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class StatusUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        exclude: Boolean = false,
        help: Boolean = false,
        org: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = StatusCommand(
            exclude = exclude,
            help = help,
            org = org,
            version = version
        )
        return repository.execute(command, context)
    }
}
