// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.gh

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class WorkflowRunUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        field: Boolean = false,
        help: Boolean = false,
        json: Boolean = false,
        rawField: Boolean = false,
        ref: Boolean = false,
        repo: Boolean = false,
        version: Boolean = false
    ): Unit {
        val command = WorkflowRunCommand(
            field = field,
            help = help,
            json = json,
            rawField = rawField,
            ref = ref,
            repo = repo,
            version = version
        )
        return repository.execute(command, context)
    }
}
