// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.zipalign.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.zipalign.*
import java.io.File

public class ZipalignCliCommand(
    private val useCase: AlignUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "zipalign") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(AlignUseCase(repository), context)

    override fun help(context: Context): String = "align or verify zip file"

    public val checkOnly: Boolean by option("--check-only", "-c", help = "check alignment only (does not modify file)").flag()
    public val overwrite: Boolean by option("--overwrite", "-f", help = "overwrite existing outfile.zip").flag()
    public val pageAlign: Boolean by option("--page-align", "-p", help = "4kb page-align uncompressed .so files").flag()
    public val pageSizeKb: Int? by option("--page-size-kb", "-P", help = "Align uncompressed .so files to specified page size (4, 16, 64)").int()
    public val verbose: Boolean by option("--verbose", "-v", help = "verbose output").flag()
    public val zopfli: Boolean by option("--zopfli", "-z", help = "recompress using Zopfli").flag()
    public val alignment: Int by argument(name = "alignment", help = "alignment in bytes (e.g. 4)").int()
    public val infile: File by argument(name = "infile", help = "input zip file").convert { File(it) }
    public val outfile: File? by argument(name = "outfile", help = "output zip file (optional in check-only mode)").convert { File(it) }.optional()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                checkOnly = checkOnly,
                overwrite = overwrite,
                pageAlign = pageAlign,
                pageSizeKb = pageSizeKb,
                verbose = verbose,
                zopfli = zopfli,
                alignment = alignment,
                infile = infile,
                outfile = outfile
            )
        }
    }
}
