// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.unpack_bootimg.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.Context
import com.github.ajalt.clikt.parameters.options.*
import com.github.ajalt.clikt.parameters.arguments.*
import com.github.ajalt.clikt.parameters.types.*
import io.ltirom.tooling.core.ExecutionContext
import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.adapters.unpack_bootimg.*
import java.io.File

public class Unpack_bootimgCliCommand(
    private val useCase: ExecuteUseCase,
    private val context: ExecutionContext
) : CliktCommand(name = "unpack_bootimg") {

    public constructor(repository: ToolRepository, context: ExecutionContext) : this(ExecuteUseCase(repository), context)

    override fun help(context: Context): String = "Execute the tool with its options and positional operands"

    public val bootImg: String? by option("--boot_img", help = "path to the boot, recovery or vendor_boot image")
    public val format: ExecuteFormatType? by option("--format", help = "{info,mkbootimg}").convert { io.ltirom.tooling.adapters.unpack_bootimg.ExecuteFormatType.valueOf(it.uppercase()) }
    public val help: Boolean by option("--help", "-h", help = "show this help message and exit").flag()
    public val nullValue: Boolean by option("--null", "-0", help = "output null-terminated argument strings").flag()
    public val out: String? by option("--out", help = "output directory of the unpacked images")
    public val positionalArgs: List<String> by argument(name = "positionalArgs", help = "Tool-specific positional operands").multiple()

    override fun run() {
        kotlinx.coroutines.runBlocking {
            useCase.execute(
                context = context,
                bootImg = bootImg,
                format = format,
                help = help,
                nullValue = nullValue,
                out = out,
                positionalArgs = positionalArgs
            )
        }
    }
}
