// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.fastboot

import io.ltirom.tooling.core.ToolCommand
import io.ltirom.tooling.core.ToolId
import io.ltirom.tooling.core.ToolRisk
import io.ltirom.tooling.core.StdinMode
import io.ltirom.tooling.core.ArtifactRequirement
import io.ltirom.tooling.core.ArtifactKind
import io.ltirom.tooling.core.ArtifactDirection
import java.io.File

public data class GetvarCommand(
    public val disableFastbootInfo: Boolean = false,
    public val disableSuperOptimization: Boolean = false,
    public val disableVerification: Boolean = false,
    public val disableVerity: Boolean = false,
    public val excludeDynamicPartitions: Boolean = false,
    public val forceOperation: Boolean = false,
    public val fsOptions: String? = null,
    public val selectDevice: String? = null,
    public val setActiveSlot: String? = null,
    public val skipReboot: Boolean = false,
    public val skipSecondarySlots: Boolean = false,
    public val slotTarget: String? = null,
    public val sparseSize: String? = null,
    public val unbufferedOutput: Boolean = false,
    public val verboseMode: Boolean = false,
    public val wipeUserdata: Boolean = false,
    public val variable: String
) : ToolCommand<Map<String, String>> {

    override val toolId: ToolId get() = ToolId.FASTBOOT
    override val risk: ToolRisk get() = ToolRisk.READ_ONLY
    override val stdinMode: StdinMode get() = StdinMode.EMPTY
    override val stdinText: String? get() = null
    override val acceptedExitCodes: Set<Int> get() = setOf(0)

    @Suppress("UNCHECKED_CAST")
    public val parser: io.ltirom.tooling.core.ToolOutputParser<Map<String, String>> get() = io.ltirom.tooling.core.ToolOutputParserRegistry.get("fastboot-vars") as io.ltirom.tooling.core.ToolOutputParser<Map<String, String>>

    override fun parseResult(result: io.ltirom.tooling.core.CommandExecutionResult): Map<String, String> {
        return parser.parse(result.stdout, result.stderr)
    }
    override fun getArguments(): List<String> {
        val args = mutableListOf<String>()
        args.add("getvar")
        if (disableFastbootInfo) args.add("--disable-fastboot-info")
        if (disableSuperOptimization) args.add("--disable-super-optimization")
        if (disableVerification) args.add("--disable-verification")
        if (disableVerity) args.add("--disable-verity")
        if (excludeDynamicPartitions) args.add("--exclude-dynamic-partitions")
        if (forceOperation) args.add("--force")
        fsOptions?.let { val value = it
            args.add("--fs-options")
            args.add(value.toString())
        }
        selectDevice?.let { val value = it
            args.add("-s")
            args.add(value.toString())
        }
        setActiveSlot?.let { val value = it
            args.add("--set-active")
            args.add(value.toString())
        }
        if (skipReboot) args.add("--skip-reboot")
        if (skipSecondarySlots) args.add("--skip-secondary")
        slotTarget?.let { val value = it
            args.add("--slot")
            args.add(value.toString())
        }
        sparseSize?.let { val value = it
            args.add("-S")
            args.add(value.toString())
        }
        if (unbufferedOutput) args.add("--unbuffered")
        if (verboseMode) args.add("--verbose")
        if (wipeUserdata) args.add("-w")
        args.add(variable.toString())
        return args
    }
}
