// This file is generated by tooling-codegen — do not edit by hand.
// Regenerate via `./gradlew :tooling-codegen:generateToolAdapters`.
package io.ltirom.tooling.adapters.repack_bootimg

import io.ltirom.tooling.core.ToolRepository
import io.ltirom.tooling.core.ExecutionContext
import java.io.File

public class ExecuteUseCase(private val repository: ToolRepository) {

    public suspend fun execute(
        context: ExecutionContext,
        dstBootimg: String? = null,
        help: Boolean = false,
        local: Boolean = false,
        ramdiskAdd: List<String> = emptyList(),
        srcBootimg: String? = null,
        positionalArgs: List<String> = emptyList()
    ): String {
        val command = ExecuteCommand(
            dstBootimg = dstBootimg,
            help = help,
            local = local,
            ramdiskAdd = ramdiskAdd,
            srcBootimg = srcBootimg,
            positionalArgs = positionalArgs
        )
        return repository.execute(command, context)
    }
}
